/*
 * Copyright (c) 2023 Texas Instruments Incorporated
 * Copyright (c) 2023 Excelfore Corporation (https://excelfore.com)
 *
 * All rights reserved not granted herein.
 * Limited License.
 *
 * Texas Instruments Incorporated grants a world-wide, royalty-free,
 * non-exclusive license under copyrights and patents it now or hereafter
 * owns or controls to make, have made, use, import, offer to sell and sell ("Utilize")
 * this software subject to the terms herein. With respect to the foregoing patent
 * license, such license is granted solely to the extent that any such patent is necessary
 * to Utilize the software alone. The patent license shall not apply to any combinations which
 * include this software, other than combinations with devices manufactured by or for TI ("TI Devices").
 * No hardware patent is licensed hereunder.
 *
 * Redistributions must preserve existing copyright notices and reproduce this license (including the
 * above copyright notice and the disclaimer and (if applicable) source code license limitations below)
 * in the documentation and/or other materials provided with the distribution
 *
 * Redistribution and use in binary form, without modification, are permitted provided that the following
 * conditions are met:
 *
 * * No reverse engineering, decompilation, or disassembly of this software is permitted with respect to any
 * software provided in binary form.
 * * any redistribution and use are licensed by TI for use only with TI Devices.
 * * Nothing shall obligate TI to provide you with source code for the software licensed and provided to you in object code.
 *
 * If software source code is provided to you, modification and redistribution of the source code are permitted
 * provided that the following conditions are met:
 *
 * * any redistribution and use of the source code, including any resulting derivative works, are licensed by
 * TI for use only with TI Devices.
 * * any redistribution and use of any object code compiled from the source code and any resulting derivative
 * works, are licensed by TI for use only with TI Devices.
 *
 * Neither the name of Texas Instruments Incorporated nor the names of its suppliers may be used to endorse or
 * promote products derived from this software without specific prior written permission.
 *
 * DISCLAIMER.
 *
 * THIS SOFTWARE IS PROVIDED BY TI AND TI"S LICENSORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL TI AND TI"S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
*/

/*
 * Copyright (c) 2008 - 2012, Andy Bierman, All Rights Reserved.
 * Copyright (c) 2012 - 2022, YumaWorks, Inc., All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */

/**
 * @file u_excelfore-interfaces.c
 * @brief User SIL-SA module for module excelfore-interfaces
 *

*** Generated by yangdump-sdk 21.10-12

<pre>

    User SIL-SA module
    bundle x4ucsilsa
    module excelfore-interfaces
    revision 2023-03-25
    prefix xl4if
    namespace urn:ieee:vendor:802.1AS:yang:xl4interfaces
    organization Excelfore Japan K.K.
    Created: 2023-03-29T06:45:58Z

Online Developer Manual:
https://www.yumaworks.com/pub/21.10/dev/yumapro-dev-manual.html

    CLI parameters:
        defnames true
        deviation excelfore-interfaces
        deviation excelfore-gptp
        format uc
        indent 4
        module ietf-interfaces
        module ieee802-dot1q-bridge
        module ieee802-dot1q-tsn-config-uni
        module excelfore-interfaces
        module ieee1588-ptp
        module ieee802-dot1as-ptp
        module excelfore-gptp
        sil-bundle x4ucsilsa
        sil-edit2
        sil-get2
        sil-include tsn_uniconf/yangs/yang_db_access.h
        sil-include tsn_uniconf/yangs/yang_modules.h
        sil-sa
        unified true

  Short Name Mappings
    duplex = /interfaces/interface/duplex
</pre>

 */

#include <xmlstring.h>

#include "procdefs.h"
#include "agt.h"
#include "agt_action.h"
#include "agt_cb.h"
#include "agt_cfg.h"
#include "agt_rpc.h"
#include "agt_sil_lib.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "agt_val.h"
#include "cfg.h"
#include "dlq.h"
#include "getcb.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "obj.h"
#include "rpc.h"
#include "sil_sa.h"
#include "status.h"
#include "val.h"
#include "val_child.h"
#include "val_util.h"
#include "xml_val.h"

#include "tsn_uniconf/yangs/yang_db_access.h"
#include "tsn_uniconf/yangs/yang_modules.h"


/* SIL bundle: x4ucsilsa */
#include "y_ietf-interfaces.h"
#include "u_ietf-interfaces.h"
#include "y_ieee802-dot1q-bridge.h"
#include "u_ieee802-dot1q-bridge.h"
#include "y_ieee802-dot1q-tsn-config-uni.h"
#include "u_ieee802-dot1q-tsn-config-uni.h"
#include "y_excelfore-interfaces.h"
#include "u_excelfore-interfaces.h"
#include "y_ieee1588-ptp.h"
#include "u_ieee1588-ptp.h"
#include "y_ieee802-dot1as-ptp.h"
#include "u_ieee802-dot1as-ptp.h"
#include "y_excelfore-gptp.h"
#include "u_excelfore-gptp.h"

/* Excelfore Uniconf Support - Start */
#include "ucclient.h"
/* Excelfore Uniconf Support - End */

/**
 * @addtogroup yang-library YANG Library
 *
 * Collection of modules supported by the server.
 * Generated by yangdump-sdk.
 */



/**
 * @addtogroup silsa-x4ucsilsa-excelfore-interfaces Module excelfore-interfaces in Bundle x4ucsilsa
 * @ingroup silsa-x4ucsilsa
 *
 * @{
 *
 * YANG instrumentation library.
 * Generated by yangdump-sdk.
 */



/* put your static variables here */


/**
 * @brief Get database object callback for leaf duplex (getcb_fn2_t)\n
 * Path: leaf /interfaces/interface/duplex\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_if_name Ancestor key leaf 'name' in list 'interface'\n
 * Path: /if:interfaces/if:interface/if:name
 * @return return status of the callback.
 */
status_t u_xl4if_duplex_get (
    getcb_get2_t *get2cb,
    const xmlChar *k_if_name)
{
    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* Excelfore Uniconf Support - Start */
    char uccfgstr[]="/ietf-interfaces/interfaces/interface/duplex";
    uint8_t aps[16];
    void *kvs[16]={NULL};
    uint8_t kss[16]={0};
    uint32_t ksize=0;
    yang_db_access_para_t dbpara={
        YANG_DB_ACTION_READ,
        YANG_DB_ONHW_NOACTION,
        NULL,
        aps,
        kvs,
        kss,
        NULL,
        0
    };
    int ucres;
    /* Excelfore Uniconf Support - End */

    if (LOGDEBUG) {
        log_debug("\nEnter u_xl4if_duplex_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* Excelfore Uniconf Support - Start */
    ucres=yang_modules_get_node_enums(NULL, uccfgstr, aps, sizeof(aps));
    if(4!=ucres) {
        log_error("\nyang_modules_get_node_enums() failed [ret=%d]", ucres);
        return ERR_NCX_NO_INSTANCE;
    }

    /* to get status data need to set RO bit */
    aps[0] |= XL4_DATA_RO;

    ucres=yang_value_conv(YANG_VTYPE_STRING, k_if_name, &kvs[0], &ksize, NULL);
    kss[0]=ucres;
    kvs[1]=NULL;

    ucres=ucclient_db_action(&dbpara);
    if(0!=ucres) {
        log_error("\nucclient_db_action(READ) failed [ret=%d]\n", ucres);
        return ERR_NCX_NO_INSTANCE;
    }

    const xmlChar *excelfore_interfaces_duplex = (xmlChar *) yang_value_string(
                                        YANG_VTYPE_ENUMERATION,
                                        dbpara.value,
                                        dbpara.vsize,
                                        0, "duplex");
    /* Excelfore Uniconf Support - End */

    /* add duplex to get2cb return_valQ */
    val_value_t *return_val = agt_make_leaf2(
        obj,
        y_xl4if_M_xl4if,
        y_xl4if_N_duplex,
        excelfore_interfaces_duplex,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    /* Excelfore Uniconf Support - Start */
    dbpara.atype=YANG_DB_ACTION_READ_RELEASE;
    ucres=ucclient_db_action(&dbpara);
    if(0!=ucres) {
        log_error("\nucclient_db_action(RELEASE) failed [ret=%d]\n", ucres);
    }

    ucclient_db_release();
    /* Excelfore Uniconf Support - End */

    return res;

} /* u_xl4if_duplex_get */



/**
 * @brief Phase 1: Initialize the excelfore-interfaces server instrumentation library.
 *
 * Called by server when module is loaded.
 *
 * @param modname requested module name to load
 * @param revision requested revision date of the module to load.
 * This may be NULL if the module has no revision statements.
 * @return return status. An error will cause the module load to fail.
 */
status_t u_excelfore_interfaces_init (
    const xmlChar *modname,
    const xmlChar *revision)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter u_excelfore_interfaces_init");
    }

    ncx_module_t *excelfore_interfaces_mod = NULL;

    excelfore_interfaces_mod = ncx_find_module(modname, revision);
    if (excelfore_interfaces_mod == NULL) {
        return ERR_NCX_OPERATION_FAILED;
    }

    /* put your module initialization code here */

    return res;

} /* u_excelfore_interfaces_init */


/**
 * @brief Phase 2: Initialize the excelfore-interfaces server instrumentation library.
 *
 * SIL init phase 2: non-config data structures.
 * Called after running config is loaded.
 *
 * @return return status. An error will cause the
 * server initialization to fail.
 */
status_t u_excelfore_interfaces_init2 (void)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter u_excelfore_interfaces_init2");
    }


    /* put your init2 code here */

    return res;

} /* u_excelfore_interfaces_init2 */


/**
 * @brief Cleanup the excelfore-interfaces server instrumentation library.
 *
 * Called by server when module is unloaded.
 *
 */
void u_excelfore_interfaces_cleanup (void)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_excelfore_interfaces_cleanup");
    }


    /* put your cleanup code here */

} /* u_excelfore_interfaces_cleanup */


 /** @} */

/* END SIL-SA u_excelfore-interfaces.c */
