/*
 * Copyright (c) 2023 Texas Instruments Incorporated
 * Copyright (c) 2023 Excelfore Corporation (https://excelfore.com)
 *
 * All rights reserved not granted herein.
 * Limited License.
 *
 * Texas Instruments Incorporated grants a world-wide, royalty-free,
 * non-exclusive license under copyrights and patents it now or hereafter
 * owns or controls to make, have made, use, import, offer to sell and sell ("Utilize")
 * this software subject to the terms herein. With respect to the foregoing patent
 * license, such license is granted solely to the extent that any such patent is necessary
 * to Utilize the software alone. The patent license shall not apply to any combinations which
 * include this software, other than combinations with devices manufactured by or for TI ("TI Devices").
 * No hardware patent is licensed hereunder.
 *
 * Redistributions must preserve existing copyright notices and reproduce this license (including the
 * above copyright notice and the disclaimer and (if applicable) source code license limitations below)
 * in the documentation and/or other materials provided with the distribution
 *
 * Redistribution and use in binary form, without modification, are permitted provided that the following
 * conditions are met:
 *
 * * No reverse engineering, decompilation, or disassembly of this software is permitted with respect to any
 * software provided in binary form.
 * * any redistribution and use are licensed by TI for use only with TI Devices.
 * * Nothing shall obligate TI to provide you with source code for the software licensed and provided to you in object code.
 *
 * If software source code is provided to you, modification and redistribution of the source code are permitted
 * provided that the following conditions are met:
 *
 * * any redistribution and use of the source code, including any resulting derivative works, are licensed by
 * TI for use only with TI Devices.
 * * any redistribution and use of any object code compiled from the source code and any resulting derivative
 * works, are licensed by TI for use only with TI Devices.
 *
 * Neither the name of Texas Instruments Incorporated nor the names of its suppliers may be used to endorse or
 * promote products derived from this software without specific prior written permission.
 *
 * DISCLAIMER.
 *
 * THIS SOFTWARE IS PROVIDED BY TI AND TI"S LICENSORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL TI AND TI"S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
*/

/*
 * Copyright (c) 2008 - 2012, Andy Bierman, All Rights Reserved.
 * Copyright (c) 2012 - 2022, YumaWorks, Inc., All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */

/**
 * @file u_ietf-interfaces.c
 * @brief User SIL-SA module for module ietf-interfaces
 *

*** Generated by yangdump-sdk 21.10-12

<pre>

    User SIL-SA module
    bundle x4ucsilsa
    module ietf-interfaces
    revision 2018-02-20
    prefix if
    namespace urn:ietf:params:xml:ns:yang:ietf-interfaces
    organization IETF NETMOD (Network Modeling) Working Group
    Created: 2023-03-29T06:45:58Z

Online Developer Manual:
https://www.yumaworks.com/pub/21.10/dev/yumapro-dev-manual.html

    CLI parameters:
        defnames true
        deviation excelfore-interfaces
        deviation excelfore-gptp
        format uc
        indent 4
        module ietf-interfaces
        module ieee802-dot1q-bridge
        module ieee802-dot1q-tsn-config-uni
        module excelfore-interfaces
        module ieee1588-ptp
        module ieee802-dot1as-ptp
        module excelfore-gptp
        sil-bundle x4ucsilsa
        sil-edit2
        sil-get2
        sil-include tsn_uniconf/yangs/yang_db_access.h
        sil-include tsn_uniconf/yangs/yang_modules.h
        sil-sa
        unified true

  Short Name Mappings
    admin_status = /interfaces/interface/admin-status
    admin_status_1 = /interfaces-state/interface/admin-status
    description = /interfaces/interface/description
    discontinuity_time = /interfaces/interface/statistics/discontinuity-time
    discontinuity_time_1 = /interfaces-state/interface/statistics/discontinuity-time
    enabled = /interfaces/interface/enabled
    higher_layer_if = /interfaces/interface/higher-layer-if
    higher_layer_if_1 = /interfaces-state/interface/higher-layer-if
    if_index = /interfaces/interface/if-index
    if_index_1 = /interfaces-state/interface/if-index
    in_broadcast_pkts = /interfaces/interface/statistics/in-broadcast-pkts
    in_broadcast_pkts_1 = /interfaces-state/interface/statistics/in-broadcast-pkts
    in_discards = /interfaces/interface/statistics/in-discards
    in_discards_1 = /interfaces-state/interface/statistics/in-discards
    in_errors = /interfaces/interface/statistics/in-errors
    in_errors_1 = /interfaces-state/interface/statistics/in-errors
    in_multicast_pkts = /interfaces/interface/statistics/in-multicast-pkts
    in_multicast_pkts_1 = /interfaces-state/interface/statistics/in-multicast-pkts
    in_octets = /interfaces/interface/statistics/in-octets
    in_octets_1 = /interfaces-state/interface/statistics/in-octets
    in_unicast_pkts = /interfaces/interface/statistics/in-unicast-pkts
    in_unicast_pkts_1 = /interfaces-state/interface/statistics/in-unicast-pkts
    in_unknown_protos = /interfaces/interface/statistics/in-unknown-protos
    in_unknown_protos_1 = /interfaces-state/interface/statistics/in-unknown-protos
    interface = /interfaces/interface
    interface_1 = /interfaces-state/interface
    interfaces = /interfaces
    interfaces_state = /interfaces-state
    last_change = /interfaces/interface/last-change
    last_change_1 = /interfaces-state/interface/last-change
    link_up_down_trap_enable = /interfaces/interface/link-up-down-trap-enable
    lower_layer_if = /interfaces/interface/lower-layer-if
    lower_layer_if_1 = /interfaces-state/interface/lower-layer-if
    name = /interfaces/interface/name
    name_1 = /interfaces-state/interface/name
    oper_status = /interfaces/interface/oper-status
    oper_status_1 = /interfaces-state/interface/oper-status
    out_broadcast_pkts = /interfaces/interface/statistics/out-broadcast-pkts
    out_broadcast_pkts_1 = /interfaces-state/interface/statistics/out-broadcast-pkts
    out_discards = /interfaces/interface/statistics/out-discards
    out_discards_1 = /interfaces-state/interface/statistics/out-discards
    out_errors = /interfaces/interface/statistics/out-errors
    out_errors_1 = /interfaces-state/interface/statistics/out-errors
    out_multicast_pkts = /interfaces/interface/statistics/out-multicast-pkts
    out_multicast_pkts_1 = /interfaces-state/interface/statistics/out-multicast-pkts
    out_octets = /interfaces/interface/statistics/out-octets
    out_octets_1 = /interfaces-state/interface/statistics/out-octets
    out_unicast_pkts = /interfaces/interface/statistics/out-unicast-pkts
    out_unicast_pkts_1 = /interfaces-state/interface/statistics/out-unicast-pkts
    phys_address = /interfaces/interface/phys-address
    phys_address_1 = /interfaces-state/interface/phys-address
    speed = /interfaces/interface/speed
    speed_1 = /interfaces-state/interface/speed
    statistics = /interfaces/interface/statistics
    statistics_1 = /interfaces-state/interface/statistics
    type = /interfaces/interface/type
    type_1 = /interfaces-state/interface/type
</pre>

 */

#include <xmlstring.h>

#include "procdefs.h"
#include "agt.h"
#include "agt_action.h"
#include "agt_cb.h"
#include "agt_cfg.h"
#include "agt_rpc.h"
#include "agt_sil_lib.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "agt_val.h"
#include "cfg.h"
#include "dlq.h"
#include "getcb.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "obj.h"
#include "rpc.h"
#include "sil_sa.h"
#include "status.h"
#include "val.h"
#include "val_child.h"
#include "val_util.h"
#include "xml_val.h"

#include "tsn_uniconf/yangs/yang_db_access.h"
#include "tsn_uniconf/yangs/yang_modules.h"


/* SIL bundle: x4ucsilsa */
#include "y_ietf-interfaces.h"
#include "u_ietf-interfaces.h"
#include "y_ieee802-dot1q-bridge.h"
#include "u_ieee802-dot1q-bridge.h"
#include "y_ieee802-dot1q-tsn-config-uni.h"
#include "u_ieee802-dot1q-tsn-config-uni.h"
#include "y_excelfore-interfaces.h"
#include "u_excelfore-interfaces.h"
#include "y_ieee1588-ptp.h"
#include "u_ieee1588-ptp.h"
#include "y_ieee802-dot1as-ptp.h"
#include "u_ieee802-dot1as-ptp.h"
#include "y_excelfore-gptp.h"
#include "u_excelfore-gptp.h"

/* Excelfore Uniconf Support - Start */
#include "ucclient.h"
/* Excelfore Uniconf Support - End */

/**
 * @addtogroup yang-library YANG Library
 *
 * Collection of modules supported by the server.
 * Generated by yangdump-sdk.
 */



/**
 * @addtogroup silsa-x4ucsilsa-ietf-interfaces Module ietf-interfaces in Bundle x4ucsilsa
 * @ingroup silsa-x4ucsilsa
 *
 * @{
 *
 * YANG instrumentation library.
 * Generated by yangdump-sdk.
 */



/* put your static variables here */


/**
 * @brief Get database object callback for leaf oper-status (getcb_fn2_t)\n
 * Path: leaf /interfaces/interface/oper-status\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_if_name Ancestor key leaf 'name' in list 'interface'\n
 * Path: /if:interfaces/if:interface/if:name
 * @return return status of the callback.
 */
status_t u_if_oper_status_get (
    getcb_get2_t *get2cb,
    const xmlChar *k_if_name)
{
    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* Excelfore Uniconf Support - Start */
    char uccfgstr[]="/ietf-interfaces/interfaces/interface/oper-status";
    uint8_t aps[16];
    void *kvs[16]={NULL};
    uint8_t kss[16]={0};
    uint32_t ksize=0;
    yang_db_access_para_t dbpara={
        YANG_DB_ACTION_READ,
        YANG_DB_ONHW_NOACTION,
        NULL,
        aps,
        kvs,
        kss,
        NULL,
        0
    };
    int ucres;
    /* Excelfore Uniconf Support - End */

    if (LOGDEBUG) {
        log_debug("\nEnter u_if_oper_status_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* Excelfore Uniconf Support - Start */
    ucres=yang_modules_get_node_enums(NULL, uccfgstr, aps, sizeof(aps));
    if(4!=ucres) {
        log_error("\nyang_modules_get_node_enums() failed [ret=%d]", ucres);
        return ERR_NCX_NO_INSTANCE;
    }

    /* to get status data need to set RO bit */
    aps[0] |= XL4_DATA_RO;

    ucres=yang_value_conv(YANG_VTYPE_STRING, k_if_name, &kvs[0], &ksize, NULL);
    kss[0]=ucres;
    kvs[1]=NULL;

    ucres=ucclient_db_action(&dbpara);
    if(0!=ucres) {
        log_error("\nucclient_db_action(READ) failed [ret=%d]\n", ucres);
        return ERR_NCX_NO_INSTANCE;
    }

    const xmlChar *v_oper_status = (xmlChar *) yang_value_string(
                                        YANG_VTYPE_ENUMERATION,
                                        dbpara.value,
                                        dbpara.vsize,
                                        0, "oper-status");
    /* Excelfore Uniconf Support - End */

    /* add oper_status to get2cb return_valQ */
    val_value_t *return_val = agt_make_leaf2(
        obj,
        y_if_M_if,
        y_if_N_oper_status,
        v_oper_status,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    /* Excelfore Uniconf Support - Start */
    dbpara.atype=YANG_DB_ACTION_READ_RELEASE;
    ucres=ucclient_db_action(&dbpara);
    if(0!=ucres) {
        log_error("\nucclient_db_action(RELEASE) failed [ret=%d]\n", ucres);
    }

    ucclient_db_release();
    /* Excelfore Uniconf Support - End */

    return res;

} /* u_if_oper_status_get */



#ifdef u_if_F_if_mib

/**
 * @brief Get database object callback for leaf if-index (getcb_fn2_t)\n
 * Path: leaf /interfaces/interface/if-index\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_if_name Ancestor key leaf 'name' in list 'interface'\n
 * Path: /if:interfaces/if:interface/if:name
 * @return return status of the callback.
 */
status_t u_if_if_index_get (
    getcb_get2_t *get2cb,
    const xmlChar *k_if_name)
{
    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* Excelfore Uniconf Support - Start */
    char uccfgstr[]="/ietf-interfaces/interfaces/interface/if-index";
    uint8_t aps[16];
    void *kvs[16]={NULL};
    uint8_t kss[16]={0};
    uint32_t ksize=0;
    yang_db_access_para_t dbpara={
        YANG_DB_ACTION_READ,
        YANG_DB_ONHW_NOACTION,
        NULL,
        aps,
        kvs,
        kss,
        NULL,
        0
    };
    int ucres;
    /* Excelfore Uniconf Support - End */

    if (LOGDEBUG) {
        log_debug("\nEnter u_if_if_index_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* Excelfore Uniconf Support - Start */
    ucres=yang_modules_get_node_enums(NULL, uccfgstr, aps, sizeof(aps));
    if(4!=ucres) {
        log_error("\nyang_modules_get_node_enums() failed [ret=%d]", ucres);
        return ERR_NCX_NO_INSTANCE;
    }

    /* to get status data need to set RO bit */
    aps[0] |= XL4_DATA_RO;

    ucres=yang_value_conv(YANG_VTYPE_STRING, k_if_name, &kvs[0], &ksize, NULL);
    kss[0]=ucres;
    kvs[1]=NULL;

    ucres=ucclient_db_action(&dbpara);
    if(0!=ucres) {
        log_error("\nucclient_db_action(READ) failed [ret=%d]\n", ucres);
        return ERR_NCX_NO_INSTANCE;
    }

    int32 v_if_index = *((int32*)dbpara.value);
    /* Excelfore Uniconf Support - End */

    /* add if_index to get2cb return_valQ */
    val_value_t *return_val = agt_make_int_leaf2(
        obj,
        y_if_M_if,
        y_if_N_if_index,
        v_if_index,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    /* Excelfore Uniconf Support - Start */
    dbpara.atype=YANG_DB_ACTION_READ_RELEASE;
    ucres=ucclient_db_action(&dbpara);
    if(0!=ucres) {
        log_error("\nucclient_db_action(RELEASE) failed [ret=%d]\n", ucres);
    }

    ucclient_db_release();
    /* Excelfore Uniconf Support - End */

    return res;

} /* u_if_if_index_get */


#endif /* u_if_F_if_mib */


/**
 * @brief Get database object callback for leaf phys-address (getcb_fn2_t)\n
 * Path: leaf /interfaces/interface/phys-address\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_if_name Ancestor key leaf 'name' in list 'interface'\n
 * Path: /if:interfaces/if:interface/if:name
 * @return return status of the callback.
 */
status_t u_if_phys_address_get (
    getcb_get2_t *get2cb,
    const xmlChar *k_if_name)
{
    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* Excelfore Uniconf Support - Start */
    char uccfgstr[]="/ietf-interfaces/interfaces/interface/phys-address";
    uint8_t aps[16];
    void *kvs[16]={NULL};
    uint8_t kss[16]={0};
    uint32_t ksize=0;
    yang_db_access_para_t dbpara={
        YANG_DB_ACTION_READ,
        YANG_DB_ONHW_NOACTION,
        NULL,
        aps,
        kvs,
        kss,
        NULL,
        0
    };
    int ucres;
    /* Excelfore Uniconf Support - End */

    if (LOGDEBUG) {
        log_debug("\nEnter u_if_phys_address_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* Excelfore Uniconf Support - Start */
    ucres=yang_modules_get_node_enums(NULL, uccfgstr, aps, sizeof(aps));
    if(4!=ucres) {
        log_error("\nyang_modules_get_node_enums() failed [ret=%d]", ucres);
        return ERR_NCX_NO_INSTANCE;
    }

    /* to get status data need to set RO bit */
    aps[0] |= XL4_DATA_RO;

    ucres=yang_value_conv(YANG_VTYPE_STRING, k_if_name, &kvs[0], &ksize, NULL);
    kss[0]=ucres;
    kvs[1]=NULL;

    ucres=ucclient_db_action(&dbpara);
    if(0!=ucres) {
        log_error("\nucclient_db_action(READ) failed [ret=%d]\n", ucres);
        return ERR_NCX_NO_INSTANCE;
    }

    const xmlChar *v_phys_address = (xmlChar *) yang_value_string(
                                        YANG_VTYPE_YANG_PHYS_ADDRESS,
                                        dbpara.value,
                                        dbpara.vsize,
                                        0,
                                        NULL);
    /* Excelfore Uniconf Support - End */

    /* add phys_address to get2cb return_valQ */
    val_value_t *return_val = agt_make_leaf2(
        obj,
        y_if_M_if,
        y_if_N_phys_address,
        v_phys_address,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    /* Excelfore Uniconf Support - Start */
    dbpara.atype=YANG_DB_ACTION_READ_RELEASE;
    ucres=ucclient_db_action(&dbpara);
    if(0!=ucres) {
        log_error("\nucclient_db_action(RELEASE) failed [ret=%d]\n", ucres);
    }

    ucclient_db_release();
    /* Excelfore Uniconf Support - End */

    return res;

} /* u_if_phys_address_get */



/**
 * @brief Get database object callback for leaf speed (getcb_fn2_t)\n
 * Path: leaf /interfaces/interface/speed\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_if_name Ancestor key leaf 'name' in list 'interface'\n
 * Path: /if:interfaces/if:interface/if:name
 * @return return status of the callback.
 */
status_t u_if_speed_get (
    getcb_get2_t *get2cb,
    const xmlChar *k_if_name)
{
    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* Excelfore Uniconf Support - Start */
    char uccfgstr[]="/ietf-interfaces/interfaces/interface/speed";
    uint8_t aps[16];
    void *kvs[16]={NULL};
    uint8_t kss[16]={0};
    uint32_t ksize=0;
    yang_db_access_para_t dbpara={
        YANG_DB_ACTION_READ,
        YANG_DB_ONHW_NOACTION,
        NULL,
        aps,
        kvs,
        kss,
        NULL,
        0
    };
    int ucres;
    /* Excelfore Uniconf Support - End */

    if (LOGDEBUG) {
        log_debug("\nEnter u_if_speed_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* Excelfore Uniconf Support - Start */
    ucres=yang_modules_get_node_enums(NULL, uccfgstr, aps, sizeof(aps));
    if(4!=ucres) {
        log_error("\nyang_modules_get_node_enums() failed [ret=%d]", ucres);
        return ERR_NCX_NO_INSTANCE;
    }

    /* to get status data need to set RO bit */
    aps[0] |= XL4_DATA_RO;

    ucres=yang_value_conv(YANG_VTYPE_STRING, k_if_name, &kvs[0], &ksize, NULL);
    kss[0]=ucres;
    kvs[1]=NULL;

    ucres=ucclient_db_action(&dbpara);
    if(0!=ucres) {
        log_error("\nucclient_db_action(READ) failed [ret=%d]\n", ucres);
        return ERR_NCX_NO_INSTANCE;
    }

    uint64 v_speed = *((uint64*)dbpara.value);
    /* Excelfore Uniconf Support - End */

    /* add speed to get2cb return_valQ */
    val_value_t *return_val = agt_make_uint64_leaf2(
        obj,
        y_if_M_if,
        y_if_N_speed,
        v_speed,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    /* Excelfore Uniconf Support - Start */
    dbpara.atype=YANG_DB_ACTION_READ_RELEASE;
    ucres=ucclient_db_action(&dbpara);
    if(0!=ucres) {
        log_error("\nucclient_db_action(RELEASE) failed [ret=%d]\n", ucres);
    }

    ucclient_db_release();
    /* Excelfore Uniconf Support - End */

    return res;

} /* u_if_speed_get */



/**
 * @brief Edit database object callback (agt_cb_fn_t)\n
 * Path: list /interfaces/interface
 *
 * @param scb session control block making the request
 * @param msg message in progress for this edit request
 * @param cbtyp callback type for this callback
 * @param editop the parent edit-config operation type,
 * which is also used for all other callbacks
 * that operate on objects.
 * @param newval container object holding the proposed changes
 * to apply to the current config, depending on
 * the editop value. Will not be NULL.
 * @param curval current container values from the "<running>"
 * or "<candidate>" configuration, if any. Could be NULL
 * for create and other operations.
 * @param k_if_name Local key leaf 'name' in list 'interface'\n
 * Path: /if:interfaces/if:interface/if:name
 * @return return status for the phase.
 */
status_t u_if_interface_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    const xmlChar *k_if_name)
{
    (void)scb;  /* remove if scb used */
    (void)msg;  /* remove if msg used */
    (void)newval;  /* remove if newval used */
    (void)curval;  /* remove if curval used */

    status_t res = NO_ERR;

    /* Excelfore Uniconf Support - Start */
    char uccfgstr[]="/ietf-interfaces/interfaces/interface/enabled";
    uint8_t aps[16];
    void *kvs[16]={NULL};
    uint8_t kss[16]={0};
    uint32_t ksize=0;
    uint32_t vsize=0;
    yang_db_access_para_t dbpara={
        YANG_DB_ACTION_CREATE,
        YANG_DB_ONHW_ALWAYS,
        NULL,
        aps,
        kvs,
        kss,
        NULL,
        0
    };
    int ucres;
    /* Excelfore Uniconf Support - End */

    if (LOGDEBUG) {
        log_debug("\nEnter u_if_interface_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    if (editop == OP_EDITOP_MERGE) {
        /* the edit is not really on this node; need to get
         * each child_undo record to get the real edited nodes */
        sil_sa_child_edit_t *child_edit  = sil_sa_first_child_edit(msg);

        while (child_edit) {
            op_editop_t child_editop = OP_EDITOP_NONE;
            val_value_t *child_newval = NULL;
            val_value_t *child_curval = NULL;

            sil_sa_child_edit_fields(child_edit,
                &child_editop,
                &child_newval,
                &child_curval);

            if (LOGDEBUG2) {
                log_debug2("\nchild edit %s", op_editop_name(child_editop));
                if (child_newval) {
                    log_debug2_append("\nnew");
                    val_dump_value(child_newval, 0, DBG2);
                }
                if (child_curval) {
                    log_debug2_append("\ncur");
                    val_dump_value(child_curval, 0, DBG2);
                }
            }

            obj_template_t *chobj = (child_newval) ?
                VAL_OBJ(child_newval) : VAL_OBJ(child_curval);
            const xmlChar *name = obj_get_name(chobj);

            /**** process child edits here ****/

            /* Excelfore Uniconf Support - Start */

            ucres=yang_value_conv(YANG_VTYPE_STRING, k_if_name, &kvs[0], &ksize, NULL);
            kss[0]=ucres;
            kvs[1]=NULL;

            if (!xml_strcmp(name, y_if_N_enabled) && AGT_CB_COMMIT == cbtyp) {
                xmlChar *newval_str = val_make_sprintf_string(child_newval);

                ucres=yang_modules_get_node_enums(NULL, uccfgstr, aps, sizeof(aps));
                if(4!=ucres) {
                    log_error("\nyang_modules_get_node_enums() failed [ret=%d]", ucres);
                    return SET_ERROR(ERR_INTERNAL_VAL);
                }

                ucres=yang_value_conv(YANG_VTYPE_BOOLEAN, (char*)newval_str,
                                      &dbpara.value, &vsize, NULL);
                m__free(newval_str);
                if(1!=ucres) {
                    log_error("\nyang_value_conv() failed [ret=%d]", ucres);
                    return SET_ERROR(ERR_INTERNAL_VAL);
                }

                dbpara.vsize=ucres;
                ucres=ucclient_db_action(&dbpara);
                if(0!=ucres) {
                    log_error("\nucclient_db_action(Update) failed [ret=%d]\n", ucres);
                    return SET_ERROR(ERR_INTERNAL_VAL);
                }

                dbpara.atype=YANG_DB_ACTION_READ_RELEASE;
                ucres=ucclient_db_action(&dbpara);
                if(0!=ucres) {
                    log_error("\nucclient_db_action(RELEASE) failed [ret=%d]\n", ucres);
                }

                ucclient_db_set_notify_aps(aps, kvs, kss);
                ucclient_db_release();
            }

            /* Excelfore Uniconf Support - End */

            child_edit = sil_sa_next_child_edit(child_edit);
        }
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        /* Excelfore Uniconf Support - Start */
        case OP_EDITOP_CREATE:
        case OP_EDITOP_DELETE:
        {
            val_value_t *child=NULL;

            if (newval) {
                child=val_get_first_child(newval);
            } else if (curval) {
                child=val_get_first_child(curval);
            }
            if(child==NULL) { break; }

            /* here we asssumed and confirm from initial check that the first child
             * of newval/curval node is the key (name) */
            xmlChar *keystr = val_make_sprintf_string(child);

            ucres=yang_value_conv(YANG_VTYPE_STRING, keystr, &kvs[0], &ksize, NULL);
            kss[0]=ucres;
            kvs[1]=NULL;

            m__free(keystr);
            child = val_get_next_child(child);

            /* at lease 1 other child leaf aside from the keys(s) should be
             * available, else we cannot add or delete it from our DB */
            if(child==NULL) { break; }

            xmlChar *valstr = val_make_sprintf_string(child);
            ucres=yang_value_conv(YANG_VTYPE_BOOLEAN, (char*)valstr,
                                  &dbpara.value, &vsize, NULL);
            m__free(valstr);
            if(1!=ucres) {
                log_error("\nyang_value_conv() failed [ret=%d]", ucres);
                return SET_ERROR(ERR_INTERNAL_VAL);
            }
            dbpara.vsize=ucres;

            if (OP_EDITOP_CREATE==editop) {
                dbpara.atype=YANG_DB_ACTION_CREATE;
            } else {
                dbpara.atype=YANG_DB_ACTION_DELETE;
            }

            ucres=yang_modules_get_node_enums(NULL, uccfgstr, aps, sizeof(aps));
            if(4!=ucres) {
                log_error("\nyang_modules_get_node_enums() failed [ret=%d]", ucres);
                return SET_ERROR(ERR_INTERNAL_VAL);
            }

            ucres=ucclient_db_action(&dbpara);
            if(0!=ucres) {
                log_error("\nucclient_db_action(%s) failed [ret=%d]\n",
                          OP_EDITOP_CREATE==editop ? "CREATE" : "DELETE", ucres);
                return SET_ERROR(ERR_INTERNAL_VAL);
            }

            dbpara.atype=YANG_DB_ACTION_READ_RELEASE;
            ucres=ucclient_db_action(&dbpara);
            if(0!=ucres) {
                log_error("\nucclient_db_action(RELEASE) failed [ret=%d]\n", ucres);
            }

            ucclient_db_set_notify_aps(aps, kvs, kss);
            ucclient_db_release();
            break;
        }
        /* Excelfore Uniconf Support - Start */
        default:
            /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_if_interface_edit */


/**
 * @brief Edit database object callback (agt_cb_fn_t)\n
 * Path: container /interfaces
 *
 * @param scb session control block making the request
 * @param msg message in progress for this edit request
 * @param cbtyp callback type for this callback
 * @param editop the parent edit-config operation type,
 * which is also used for all other callbacks
 * that operate on objects.
 * @param newval container object holding the proposed changes
 * to apply to the current config, depending on
 * the editop value. Will not be NULL.
 * @param curval current container values from the "<running>"
 * or "<candidate>" configuration, if any. Could be NULL
 * for create and other operations.
 * @return return status for the phase.
 */
status_t u_if_interfaces_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    (void)scb;  /* remove if scb used */
    (void)msg;  /* remove if msg used */
    (void)newval;  /* remove if newval used */
    (void)curval;  /* remove if curval used */

    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter u_if_interfaces_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_if_interfaces_edit */


/**
 * @brief Phase 1: Initialize the ietf-interfaces server instrumentation library.
 *
 * Called by server when module is loaded.
 *
 * @param modname requested module name to load
 * @param revision requested revision date of the module to load.
 * This may be NULL if the module has no revision statements.
 * @return return status. An error will cause the module load to fail.
 */
status_t u_ietf_interfaces_init (
    const xmlChar *modname,
    const xmlChar *revision)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter u_ietf_interfaces_init");
    }

    ncx_module_t *ietf_interfaces_mod = NULL;

    ietf_interfaces_mod = ncx_find_module(modname, revision);
    if (ietf_interfaces_mod == NULL) {
        return ERR_NCX_OPERATION_FAILED;
    }

    /* put your module initialization code here */

    return res;

} /* u_ietf_interfaces_init */


/**
 * @brief Phase 2: Initialize the ietf-interfaces server instrumentation library.
 *
 * SIL init phase 2: non-config data structures.
 * Called after running config is loaded.
 *
 * @return return status. An error will cause the
 * server initialization to fail.
 */
status_t u_ietf_interfaces_init2 (void)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter u_ietf_interfaces_init2");
    }


    /* put your init2 code here */

    return res;

} /* u_ietf_interfaces_init2 */


/**
 * @brief Cleanup the ietf-interfaces server instrumentation library.
 *
 * Called by server when module is unloaded.
 *
 */
void u_ietf_interfaces_cleanup (void)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_ietf_interfaces_cleanup");
    }


    /* put your cleanup code here */

} /* u_ietf_interfaces_cleanup */


 /** @} */

/* END SIL-SA u_ietf-interfaces.c */
