/*
 * Copyright (c) 2023 Texas Instruments Incorporated
 * Copyright (c) 2023 Excelfore Corporation (https://excelfore.com)
 *
 * All rights reserved not granted herein.
 * Limited License.
 *
 * Texas Instruments Incorporated grants a world-wide, royalty-free,
 * non-exclusive license under copyrights and patents it now or hereafter
 * owns or controls to make, have made, use, import, offer to sell and sell ("Utilize")
 * this software subject to the terms herein. With respect to the foregoing patent
 * license, such license is granted solely to the extent that any such patent is necessary
 * to Utilize the software alone. The patent license shall not apply to any combinations which
 * include this software, other than combinations with devices manufactured by or for TI ("TI Devices").
 * No hardware patent is licensed hereunder.
 *
 * Redistributions must preserve existing copyright notices and reproduce this license (including the
 * above copyright notice and the disclaimer and (if applicable) source code license limitations below)
 * in the documentation and/or other materials provided with the distribution
 *
 * Redistribution and use in binary form, without modification, are permitted provided that the following
 * conditions are met:
 *
 * * No reverse engineering, decompilation, or disassembly of this software is permitted with respect to any
 * software provided in binary form.
 * * any redistribution and use are licensed by TI for use only with TI Devices.
 * * Nothing shall obligate TI to provide you with source code for the software licensed and provided to you in object code.
 *
 * If software source code is provided to you, modification and redistribution of the source code are permitted
 * provided that the following conditions are met:
 *
 * * any redistribution and use of the source code, including any resulting derivative works, are licensed by
 * TI for use only with TI Devices.
 * * any redistribution and use of any object code compiled from the source code and any resulting derivative
 * works, are licensed by TI for use only with TI Devices.
 *
 * Neither the name of Texas Instruments Incorporated nor the names of its suppliers may be used to endorse or
 * promote products derived from this software without specific prior written permission.
 *
 * DISCLAIMER.
 *
 * THIS SOFTWARE IS PROVIDED BY TI AND TI"S LICENSORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL TI AND TI"S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
*/

/*
 * Copyright (c) 2008 - 2012, Andy Bierman, All Rights Reserved.
 * Copyright (c) 2012 - 2022, YumaWorks, Inc., All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */

/**
 * @file u_ieee802-dot1as-ptp.c
 * @brief User SIL-SA module for module ieee802-dot1as-ptp
 *

*** Generated by yangdump-sdk 21.10-12

<pre>

    User SIL-SA module
    bundle x4ucsilsa
    module ieee802-dot1as-ptp
    revision 2022-12-14
    prefix dot1as-ptp
    namespace urn:ieee:std:802.1AS:yang:ieee802-dot1as-ptp
    organization IEEE 802.1 Working Group
    Created: 2023-03-29T06:45:58Z

Online Developer Manual:
https://www.yumaworks.com/pub/21.10/dev/yumapro-dev-manual.html

    CLI parameters:
        defnames true
        deviation excelfore-interfaces
        deviation excelfore-gptp
        format uc
        indent 4
        module ietf-interfaces
        module ieee802-dot1q-bridge
        module ieee802-dot1q-tsn-config-uni
        module excelfore-interfaces
        module ieee1588-ptp
        module ieee802-dot1as-ptp
        module excelfore-gptp
        sil-bundle x4ucsilsa
        sil-edit2
        sil-get2
        sil-include tsn_uniconf/yangs/yang_db_access.h
        sil-include tsn_uniconf/yangs/yang_modules.h
        sil-sa
        unified true

  Short Name Mappings
    allowed_faults = /ptp/instances/instance/ports/port/port-ds/allowed-faults
    allowed_faults_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/allowed-faults
    allowed_lost_responses = /ptp/instances/instance/ports/port/port-ds/allowed-lost-responses
    allowed_lost_responses_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/allowed-lost-responses
    announce_receipt_timeout_count = /ptp/instances/instance/ports/port/port-statistics-ds/announce-receipt-timeout-count
    as_capable = /ptp/instances/instance/ports/port/port-ds/as-capable
    as_capable_across_domains = /ptp/common-services/cmlds/ports/port/link-port-ds/as-capable-across-domains
    asymmetry_measurement_mode_ds = /ptp/instances/instance/ports/port/asymmetry-measurement-mode-ds
    asymmetry_measurement_mode_ds_1 = /ptp/common-services/cmlds/ports/port/asymmetry-measurement-mode-ds
    cmlds_link_port_enabled = /ptp/common-services/cmlds/ports/port/link-port-ds/cmlds-link-port-enabled
    cumulative_rate_ratio = /ptp/instances/instance/parent-ds/cumulative-rate-ratio
    current_compute_mean_link_delay = /ptp/instances/instance/ports/port/port-ds/current-compute-mean-link-delay
    current_compute_mean_link_delay_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/current-compute-mean-link-delay
    current_compute_rate_ratio = /ptp/instances/instance/ports/port/port-ds/current-compute-rate-ratio
    current_compute_rate_ratio_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/current-compute-rate-ratio
    current_log_announce_interval = /ptp/instances/instance/ports/port/port-ds/current-log-announce-interval
    current_log_gptp_cap_interval = /ptp/instances/instance/ports/port/port-ds/current-log-gptp-cap-interval
    current_log_pdelay_req_interval = /ptp/instances/instance/ports/port/port-ds/current-log-pdelay-req-interval
    current_log_pdelay_req_interval_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/current-log-pdelay-req-interval
    current_log_sync_interval = /ptp/instances/instance/ports/port/port-ds/current-log-sync-interval
    current_one_step_tx_oper = /ptp/instances/instance/ports/port/port-ds/current-one-step-tx-oper
    current_utc_offset = /ptp/instances/instance/default-ds/current-utc-offset
    current_utc_offset_valid = /ptp/instances/instance/default-ds/current-utc-offset-valid
    enabled = /ptp/instances/instance/ports/port/asymmetry-measurement-mode-ds/enabled
    enabled_1 = /ptp/common-services/cmlds/ports/port/asymmetry-measurement-mode-ds/enabled
    frequency_traceable = /ptp/instances/instance/default-ds/frequency-traceable
    gm_capable = /ptp/instances/instance/default-ds/gm-capable
    gm_change_count = /ptp/instances/instance/current-ds/gm-change-count
    gm_timebase_indicator = /ptp/instances/instance/current-ds/gm-timebase-indicator
    gptp_cap_receipt_timeout = /ptp/instances/instance/ports/port/port-ds/gptp-cap-receipt-timeout
    initial_compute_mean_link_delay = /ptp/instances/instance/ports/port/port-ds/initial-compute-mean-link-delay
    initial_compute_mean_link_delay_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/initial-compute-mean-link-delay
    initial_compute_rate_ratio = /ptp/instances/instance/ports/port/port-ds/initial-compute-rate-ratio
    initial_compute_rate_ratio_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/initial-compute-rate-ratio
    initial_log_announce_interval = /ptp/instances/instance/ports/port/port-ds/initial-log-announce-interval
    initial_log_gptp_cap_interval = /ptp/instances/instance/ports/port/port-ds/initial-log-gptp-cap-interval
    initial_log_pdelay_req_interval = /ptp/instances/instance/ports/port/port-ds/initial-log-pdelay-req-interval
    initial_log_pdelay_req_interval_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/initial-log-pdelay-req-interval
    initial_log_sync_interval = /ptp/instances/instance/ports/port/port-ds/initial-log-sync-interval
    initial_one_step_tx_oper = /ptp/instances/instance/ports/port/port-ds/initial-one-step-tx-oper
    is_measuring_delay = /ptp/instances/instance/ports/port/port-ds/is-measuring-delay
    is_measuring_delay_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/is-measuring-delay
    last_gm_freq_change = /ptp/instances/instance/current-ds/last-gm-freq-change
    last_gm_phase_change = /ptp/instances/instance/current-ds/last-gm-phase-change
    leap59 = /ptp/instances/instance/default-ds/leap59
    leap61 = /ptp/instances/instance/default-ds/leap61
    mean_link_delay_thresh = /ptp/instances/instance/ports/port/port-ds/mean-link-delay-thresh
    mean_link_delay_thresh_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/mean-link-delay-thresh
    mgt_compute_mean_link_delay = /ptp/instances/instance/ports/port/port-ds/mgt-compute-mean-link-delay
    mgt_compute_mean_link_delay_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/mgt-compute-mean-link-delay
    mgt_compute_rate_ratio = /ptp/instances/instance/ports/port/port-ds/mgt-compute-rate-ratio
    mgt_compute_rate_ratio_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/mgt-compute-rate-ratio
    mgt_log_gptp_cap_interval = /ptp/instances/instance/ports/port/port-ds/mgt-log-gptp-cap-interval
    mgt_log_pdelay_req_interval = /ptp/instances/instance/ports/port/port-ds/mgt-log-pdelay-req-interval
    mgt_log_pdelay_req_interval_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/mgt-log-pdelay-req-interval
    mgt_one_step_tx_oper = /ptp/instances/instance/ports/port/port-ds/mgt-one-step-tx-oper
    ndown = /ptp/instances/instance/ports/port/port-ds/ndown
    neighbor_rate_ratio = /ptp/instances/instance/ports/port/port-ds/neighbor-rate-ratio
    nup = /ptp/instances/instance/ports/port/port-ds/nup
    one_step_receive = /ptp/instances/instance/ports/port/port-ds/one-step-receive
    one_step_transmit = /ptp/instances/instance/ports/port/port-ds/one-step-transmit
    one_step_tx_oper = /ptp/instances/instance/ports/port/port-ds/one-step-tx-oper
    pdelay_allowed_lost_exceeded_count = /ptp/instances/instance/ports/port/port-statistics-ds/pdelay-allowed-lost-exceeded-count
    pdelay_allowed_lost_exceeded_count_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds/pdelay-allowed-lost-exceeded-count
    pdelay_truncated_timestamps = /ptp/instances/instance/ports/port/port-ds/pdelay-truncated-timestamps
    pdelay_truncated_timestamps_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/pdelay-truncated-timestamps
    port_statistics_ds = /ptp/instances/instance/ports/port/port-statistics-ds
    port_statistics_ds_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds
    ptp_timescale = /ptp/instances/instance/default-ds/ptp-timescale
    rx_announce_count = /ptp/instances/instance/ports/port/port-statistics-ds/rx-announce-count
    rx_follow_up_count = /ptp/instances/instance/ports/port/port-statistics-ds/rx-follow-up-count
    rx_one_step_sync_count = /ptp/instances/instance/ports/port/port-statistics-ds/rx-one-step-sync-count
    rx_packet_discard_count = /ptp/instances/instance/ports/port/port-statistics-ds/rx-packet-discard-count
    rx_packet_discard_count_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds/rx-packet-discard-count
    rx_pdelay_req_count = /ptp/instances/instance/ports/port/port-statistics-ds/rx-pdelay-req-count
    rx_pdelay_req_count_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds/rx-pdelay-req-count
    rx_pdelay_resp_count = /ptp/instances/instance/ports/port/port-statistics-ds/rx-pdelay-resp-count
    rx_pdelay_resp_count_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds/rx-pdelay-resp-count
    rx_pdelay_resp_follow_up_count = /ptp/instances/instance/ports/port/port-statistics-ds/rx-pdelay-resp-follow-up-count
    rx_pdelay_resp_follow_up_count_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds/rx-pdelay-resp-follow-up-count
    rx_sync_count = /ptp/instances/instance/ports/port/port-statistics-ds/rx-sync-count
    sync_locked = /ptp/instances/instance/ports/port/port-ds/sync-locked
    sync_receipt_timeout = /ptp/instances/instance/ports/port/port-ds/sync-receipt-timeout
    sync_receipt_timeout_count = /ptp/instances/instance/ports/port/port-statistics-ds/sync-receipt-timeout-count
    sync_receipt_timeout_interval = /ptp/instances/instance/ports/port/port-ds/sync-receipt-timeout-interval
    time_of_last_freq_change = /ptp/instances/instance/current-ds/time-of-last-freq-change
    time_of_last_gm_change = /ptp/instances/instance/current-ds/time-of-last-gm-change
    time_of_last_phase_change = /ptp/instances/instance/current-ds/time-of-last-phase-change
    time_source = /ptp/instances/instance/default-ds/time-source
    time_traceable = /ptp/instances/instance/default-ds/time-traceable
    tx_announce_count = /ptp/instances/instance/ports/port/port-statistics-ds/tx-announce-count
    tx_follow_up_count = /ptp/instances/instance/ports/port/port-statistics-ds/tx-follow-up-count
    tx_one_step_sync_count = /ptp/instances/instance/ports/port/port-statistics-ds/tx-one-step-sync-count
    tx_pdelay_req_count = /ptp/instances/instance/ports/port/port-statistics-ds/tx-pdelay-req-count
    tx_pdelay_req_count_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds/tx-pdelay-req-count
    tx_pdelay_resp_count = /ptp/instances/instance/ports/port/port-statistics-ds/tx-pdelay-resp-count
    tx_pdelay_resp_count_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds/tx-pdelay-resp-count
    tx_pdelay_resp_follow_up_count = /ptp/instances/instance/ports/port/port-statistics-ds/tx-pdelay-resp-follow-up-count
    tx_pdelay_resp_follow_up_count_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds/tx-pdelay-resp-follow-up-count
    tx_sync_count = /ptp/instances/instance/ports/port/port-statistics-ds/tx-sync-count
    use_mgt_compute_mean_link_delay = /ptp/instances/instance/ports/port/port-ds/use-mgt-compute-mean-link-delay
    use_mgt_compute_mean_link_delay_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/use-mgt-compute-mean-link-delay
    use_mgt_compute_rate_ratio = /ptp/instances/instance/ports/port/port-ds/use-mgt-compute-rate-ratio
    use_mgt_compute_rate_ratio_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/use-mgt-compute-rate-ratio
    use_mgt_log_announce_interval = /ptp/instances/instance/ports/port/port-ds/use-mgt-log-announce-interval
    use_mgt_log_gptp_cap_interval = /ptp/instances/instance/ports/port/port-ds/use-mgt-log-gptp-cap-interval
    use_mgt_log_pdelay_req_interval = /ptp/instances/instance/ports/port/port-ds/use-mgt-log-pdelay-req-interval
    use_mgt_log_pdelay_req_interval_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/use-mgt-log-pdelay-req-interval
    use_mgt_log_sync_interval = /ptp/instances/instance/ports/port/port-ds/use-mgt-log-sync-interval
    use_mgt_one_step_tx_oper = /ptp/instances/instance/ports/port/port-ds/use-mgt-one-step-tx-oper
</pre>

 */

#include <xmlstring.h>

#include "procdefs.h"
#include "agt.h"
#include "agt_action.h"
#include "agt_cb.h"
#include "agt_cfg.h"
#include "agt_rpc.h"
#include "agt_sil_lib.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "agt_val.h"
#include "cfg.h"
#include "dlq.h"
#include "getcb.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "obj.h"
#include "rpc.h"
#include "sil_sa.h"
#include "status.h"
#include "val.h"
#include "val_child.h"
#include "val_util.h"
#include "xml_val.h"

#include "tsn_uniconf/yangs/yang_db_access.h"
#include "tsn_uniconf/yangs/yang_modules.h"


/* SIL bundle: x4ucsilsa */
#include "y_ietf-interfaces.h"
#include "u_ietf-interfaces.h"
#include "y_ieee802-dot1q-bridge.h"
#include "u_ieee802-dot1q-bridge.h"
#include "y_ieee802-dot1q-tsn-config-uni.h"
#include "u_ieee802-dot1q-tsn-config-uni.h"
#include "y_excelfore-interfaces.h"
#include "u_excelfore-interfaces.h"
#include "y_ieee1588-ptp.h"
#include "u_ieee1588-ptp.h"
#include "y_ieee802-dot1as-ptp.h"
#include "u_ieee802-dot1as-ptp.h"
#include "y_excelfore-gptp.h"
#include "u_excelfore-gptp.h"


/**
 * @addtogroup yang-library YANG Library
 *
 * Collection of modules supported by the server.
 * Generated by yangdump-sdk.
 */



/**
 * @addtogroup silsa-x4ucsilsa-ieee802-dot1as-ptp Module ieee802-dot1as-ptp in Bundle x4ucsilsa
 * @ingroup silsa-x4ucsilsa
 *
 * @{
 *
 * YANG instrumentation library.
 * Generated by yangdump-sdk.
 */



/* put your static variables here */


/**
 * @brief Get database object callback for leaf gm-capable (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/gm-capable\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_gm_capable_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_gm_capable_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_gm_capable = 0;

    /* add gm_capable to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_gm_capable,
        ieee802_dot1as_ptp_gm_capable,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_gm_capable_get */



/**
 * @brief Get database object callback for leaf current-utc-offset (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/current-utc-offset\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_current_utc_offset_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_current_utc_offset_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    int16 ieee802_dot1as_ptp_current_utc_offset = 0;

    /* add current_utc_offset to get2cb return_valQ */
    val_value_t *return_val = agt_make_int_leaf2(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_current_utc_offset,
        ieee802_dot1as_ptp_current_utc_offset,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_current_utc_offset_get */



/**
 * @brief Get database object callback for leaf current-utc-offset-valid (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/current-utc-offset-valid\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_current_utc_offset_valid_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_current_utc_offset_valid_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_current_utc_offset_valid = 0;

    /* add current_utc_offset_valid to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_current_utc_offset_valid,
        ieee802_dot1as_ptp_current_utc_offset_valid,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_current_utc_offset_valid_get */



/**
 * @brief Get database object callback for leaf leap59 (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/leap59\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_leap59_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_leap59_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_leap59 = 0;

    /* add leap59 to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_leap59,
        ieee802_dot1as_ptp_leap59,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_leap59_get */



/**
 * @brief Get database object callback for leaf leap61 (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/leap61\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_leap61_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_leap61_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_leap61 = 0;

    /* add leap61 to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_leap61,
        ieee802_dot1as_ptp_leap61,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_leap61_get */



/**
 * @brief Get database object callback for leaf time-traceable (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/time-traceable\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_time_traceable_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_time_traceable_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_time_traceable = 0;

    /* add time_traceable to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_time_traceable,
        ieee802_dot1as_ptp_time_traceable,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_time_traceable_get */



/**
 * @brief Get database object callback for leaf frequency-traceable (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/frequency-traceable\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_frequency_traceable_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_frequency_traceable_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_frequency_traceable = 0;

    /* add frequency_traceable to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_frequency_traceable,
        ieee802_dot1as_ptp_frequency_traceable,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_frequency_traceable_get */



/**
 * @brief Get database object callback for leaf ptp-timescale (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/ptp-timescale\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_ptp_timescale_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_ptp_timescale_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_ptp_timescale = 0;

    /* add ptp_timescale to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_ptp_timescale,
        ieee802_dot1as_ptp_ptp_timescale,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_ptp_timescale_get */



/**
 * @brief Get database object callback for leaf time-source (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/time-source\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_time_source_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_time_source_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    const xmlChar *ieee802_dot1as_ptp_time_source = 0;

    /* add time_source to get2cb return_valQ */
    val_value_t *return_val = agt_make_leaf2(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_time_source,
        ieee802_dot1as_ptp_time_source,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_time_source_get */



/**
 * @brief Get database object callback for leaf is-measuring-delay (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/is-measuring-delay\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_is_measuring_delay_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_is_measuring_delay_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_is_measuring_delay = 0;

    /* add is_measuring_delay to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_is_measuring_delay,
        ieee802_dot1as_ptp_is_measuring_delay,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_is_measuring_delay_get */



/**
 * @brief Get database object callback for leaf as-capable (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/as-capable\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_as_capable_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_as_capable_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_as_capable = 0;

    /* add as_capable to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_as_capable,
        ieee802_dot1as_ptp_as_capable,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_as_capable_get */



/**
 * @brief Get database object callback for leaf neighbor-rate-ratio (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/neighbor-rate-ratio\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_neighbor_rate_ratio_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_neighbor_rate_ratio_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    int32 ieee802_dot1as_ptp_neighbor_rate_ratio = 0;

    /* add neighbor_rate_ratio to get2cb return_valQ */
    val_value_t *return_val = agt_make_int_leaf2(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_neighbor_rate_ratio,
        ieee802_dot1as_ptp_neighbor_rate_ratio,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_neighbor_rate_ratio_get */



/**
 * @brief Get database object callback for leaf current-log-announce-interval (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/current-log-announce-interval\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_current_log_announce_interval_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_current_log_announce_interval_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    int8 ieee802_dot1as_ptp_current_log_announce_interval = 0;

    /* add current_log_announce_interval to get2cb return_valQ */
    val_value_t *return_val = agt_make_int_leaf2(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_current_log_announce_interval,
        ieee802_dot1as_ptp_current_log_announce_interval,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_current_log_announce_interval_get */



/**
 * @brief Get database object callback for leaf use-mgt-log-announce-interval (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/use-mgt-log-announce-interval\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_use_mgt_log_announce_interval_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_use_mgt_log_announce_interval_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_use_mgt_log_announce_interval = 0;

    /* add use_mgt_log_announce_interval to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_use_mgt_log_announce_interval,
        ieee802_dot1as_ptp_use_mgt_log_announce_interval,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_use_mgt_log_announce_interval_get */



/**
 * @brief Get database object callback for leaf current-log-sync-interval (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/current-log-sync-interval\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_current_log_sync_interval_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_current_log_sync_interval_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    int8 ieee802_dot1as_ptp_current_log_sync_interval = 0;

    /* add current_log_sync_interval to get2cb return_valQ */
    val_value_t *return_val = agt_make_int_leaf2(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_current_log_sync_interval,
        ieee802_dot1as_ptp_current_log_sync_interval,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_current_log_sync_interval_get */



/**
 * @brief Get database object callback for leaf use-mgt-log-sync-interval (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/use-mgt-log-sync-interval\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_use_mgt_log_sync_interval_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_use_mgt_log_sync_interval_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_use_mgt_log_sync_interval = 0;

    /* add use_mgt_log_sync_interval to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_use_mgt_log_sync_interval,
        ieee802_dot1as_ptp_use_mgt_log_sync_interval,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_use_mgt_log_sync_interval_get */



/**
 * @brief Get database object callback for leaf sync-receipt-timeout-interval (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/sync-receipt-timeout-interval\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_sync_receipt_timeout_interval_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_sync_receipt_timeout_interval_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    const xmlChar *ieee802_dot1as_ptp_sync_receipt_timeout_interval = 0;

    /* add sync_receipt_timeout_interval to get2cb return_valQ */
    val_value_t *return_val = agt_make_leaf2(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_sync_receipt_timeout_interval,
        ieee802_dot1as_ptp_sync_receipt_timeout_interval,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_sync_receipt_timeout_interval_get */



/**
 * @brief Get database object callback for leaf current-log-pdelay-req-interval (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/current-log-pdelay-req-interval\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_current_log_pdelay_req_interval_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_current_log_pdelay_req_interval_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    int8 ieee802_dot1as_ptp_current_log_pdelay_req_interval = 0;

    /* add current_log_pdelay_req_interval to get2cb return_valQ */
    val_value_t *return_val = agt_make_int_leaf2(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_current_log_pdelay_req_interval,
        ieee802_dot1as_ptp_current_log_pdelay_req_interval,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_current_log_pdelay_req_interval_get */



/**
 * @brief Get database object callback for leaf use-mgt-log-pdelay-req-interval (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/use-mgt-log-pdelay-req-interval\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_use_mgt_log_pdelay_req_interval_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_use_mgt_log_pdelay_req_interval_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_use_mgt_log_pdelay_req_interval = 0;

    /* add use_mgt_log_pdelay_req_interval to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_use_mgt_log_pdelay_req_interval,
        ieee802_dot1as_ptp_use_mgt_log_pdelay_req_interval,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_use_mgt_log_pdelay_req_interval_get */



/**
 * @brief Get database object callback for leaf current-log-gptp-cap-interval (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/current-log-gptp-cap-interval\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_current_log_gptp_cap_interval_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_current_log_gptp_cap_interval_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    int8 ieee802_dot1as_ptp_current_log_gptp_cap_interval = 0;

    /* add current_log_gptp_cap_interval to get2cb return_valQ */
    val_value_t *return_val = agt_make_int_leaf2(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_current_log_gptp_cap_interval,
        ieee802_dot1as_ptp_current_log_gptp_cap_interval,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_current_log_gptp_cap_interval_get */



/**
 * @brief Get database object callback for leaf use-mgt-compute-rate-ratio (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/use-mgt-compute-rate-ratio\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_use_mgt_compute_rate_ratio_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_use_mgt_compute_rate_ratio_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_use_mgt_compute_rate_ratio = 0;

    /* add use_mgt_compute_rate_ratio to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_use_mgt_compute_rate_ratio,
        ieee802_dot1as_ptp_use_mgt_compute_rate_ratio,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_use_mgt_compute_rate_ratio_get */



/**
 * @brief Get database object callback for leaf use-mgt-compute-mean-link-delay (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/use-mgt-compute-mean-link-delay\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_use_mgt_compute_mean_link_delay_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_use_mgt_compute_mean_link_delay_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_use_mgt_compute_mean_link_delay = 0;

    /* add use_mgt_compute_mean_link_delay to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_use_mgt_compute_mean_link_delay,
        ieee802_dot1as_ptp_use_mgt_compute_mean_link_delay,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_use_mgt_compute_mean_link_delay_get */



/**
 * @brief Get database object callback for leaf one-step-tx-oper (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/one-step-tx-oper\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_one_step_tx_oper_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_one_step_tx_oper_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_one_step_tx_oper = 0;

    /* add one_step_tx_oper to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_one_step_tx_oper,
        ieee802_dot1as_ptp_one_step_tx_oper,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_one_step_tx_oper_get */



/**
 * @brief Get database object callback for leaf one-step-receive (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/one-step-receive\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_one_step_receive_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_one_step_receive_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_one_step_receive = 0;

    /* add one_step_receive to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_one_step_receive,
        ieee802_dot1as_ptp_one_step_receive,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_one_step_receive_get */



/**
 * @brief Get database object callback for leaf one-step-transmit (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/one-step-transmit\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_one_step_transmit_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_one_step_transmit_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_one_step_transmit = 0;

    /* add one_step_transmit to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_one_step_transmit,
        ieee802_dot1as_ptp_one_step_transmit,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_one_step_transmit_get */



/**
 * @brief Get database object callback for leaf initial-one-step-tx-oper (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/initial-one-step-tx-oper\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_initial_one_step_tx_oper_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_initial_one_step_tx_oper_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    int8 ieee802_dot1as_ptp_initial_one_step_tx_oper = 0;

    /* add initial_one_step_tx_oper to get2cb return_valQ */
    val_value_t *return_val = agt_make_int_leaf2(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_initial_one_step_tx_oper,
        ieee802_dot1as_ptp_initial_one_step_tx_oper,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_initial_one_step_tx_oper_get */



/**
 * @brief Get database object callback for leaf current-one-step-tx-oper (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/current-one-step-tx-oper\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_current_one_step_tx_oper_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_current_one_step_tx_oper_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    int8 ieee802_dot1as_ptp_current_one_step_tx_oper = 0;

    /* add current_one_step_tx_oper to get2cb return_valQ */
    val_value_t *return_val = agt_make_int_leaf2(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_current_one_step_tx_oper,
        ieee802_dot1as_ptp_current_one_step_tx_oper,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_current_one_step_tx_oper_get */



/**
 * @brief Get database object callback for leaf use-mgt-one-step-tx-oper (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/use-mgt-one-step-tx-oper\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_use_mgt_one_step_tx_oper_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_use_mgt_one_step_tx_oper_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    boolean ieee802_dot1as_ptp_use_mgt_one_step_tx_oper = 0;

    /* add use_mgt_one_step_tx_oper to get2cb return_valQ */
    val_value_t *return_val = agt_make_boolean_leaf(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_use_mgt_one_step_tx_oper,
        ieee802_dot1as_ptp_use_mgt_one_step_tx_oper,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_use_mgt_one_step_tx_oper_get */



/**
 * @brief Get database object callback for leaf mgt-one-step-tx-oper (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/mgt-one-step-tx-oper\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_mgt_one_step_tx_oper_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_mgt_one_step_tx_oper_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get the real value from the system somehow */
    int8 ieee802_dot1as_ptp_mgt_one_step_tx_oper = 0;

    /* add mgt_one_step_tx_oper to get2cb return_valQ */
    val_value_t *return_val = agt_make_int_leaf2(
        obj,
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_N_mgt_one_step_tx_oper,
        ieee802_dot1as_ptp_mgt_one_step_tx_oper,
        &res);
    if (return_val) {
        getcb_add_return_val(get2cb, return_val);
    }

    return res;

} /* u_dot1as_ptp_mgt_one_step_tx_oper_get */



/**
 * @brief Get database object callback for leaf-list pdelay-truncated-timestamps (getcb_fn2_t)\n
 * Path: leaf-list /ptp/instances/instance/ports/port/port-ds/pdelay-truncated-timestamps\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_pdelay_truncated_timestamps_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_pdelay_truncated_timestamps_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* check if the requested node exists; determined by the
     * SIL or SIL-SA callback based on instances in the system
     * CHANGE node_exists TO TRUE WHEN VALUE CODE FILLED IN */
    boolean node_exists = FALSE;

    if (!node_exists) {
        return ERR_NCX_NO_INSTANCE;
    }

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* get all the instances of this leaf-list and add a val_value_t
     * for each one with the getcb_add_return_val function
     */

    return res;

} /* u_dot1as_ptp_pdelay_truncated_timestamps_get */



/**
 * @brief Get database object callback for container port-statistics-ds (getcb_fn2_t)\n
 * Path: container /ptp/instances/instance/ports/port/port-statistics-ds\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param get2cb GET2 control block for the callback.
 * @param k_ptp_instance_index Ancestor key leaf 'instance-index' in list 'instance'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:instance-index
 * @param k_ptp_port_index Ancestor key leaf 'port-index' in list 'port'\n
 * Path: /ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-index
 * @return return status of the callback.
 */
status_t u_dot1as_ptp_port_statistics_ds_get (
    getcb_get2_t *get2cb,
    uint32 k_ptp_instance_index,
    uint16 k_ptp_port_index)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_dot1as_ptp_port_statistics_ds_get");
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        /* USE SET_ERROR FOR PROGRAMMING BUGS ONLY */
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* an NP container always exists so no test for node_exists
     * by the SIL or SIL-SA callback is needed
     */
    /* optional: check if any content-match nodes are present */
    boolean match_test_done = FALSE;
    val_value_t *match_val = GETCB_GET2_FIRST_MATCH(get2cb);
    for (; match_val; match_val =
        GETCB_GET2_NEXT_MATCH(get2cb, match_val)) {

        /**** CHECK CONTENT NODES AGAINST THIS ENTRY ***/

    }
    GETCB_GET2_MATCH_TEST_DONE(get2cb) = match_test_done;

    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* go through all the requested terminal child objects */
    obj_template_t *childobj =
        getcb_first_requested_child(get2cb, obj);
    for (; childobj; childobj =
        getcb_next_requested_child(get2cb, childobj)) {

        const xmlChar *name = obj_get_name(childobj);

        /* Retrieve the value of this terminal node and
         * add with getcb_add_return_val */

        if (!xml_strcmp(name, y_dot1as_ptp_N_rx_sync_count)) {
            /* leaf rx-sync-count (uint32) */

        } else if (!xml_strcmp(name, y_dot1as_ptp_N_rx_one_step_sync_count)) {
            /* leaf rx-one-step-sync-count (uint32) */

        } else if (!xml_strcmp(name, y_dot1as_ptp_N_rx_follow_up_count)) {
            /* leaf rx-follow-up-count (uint32) */

        } else if (!xml_strcmp(name, y_dot1as_ptp_N_rx_pdelay_req_count)) {
            /* leaf rx-pdelay-req-count (uint32) */

        } else if (!xml_strcmp(name, y_dot1as_ptp_N_rx_pdelay_resp_count)) {
            /* leaf rx-pdelay-resp-count (uint32) */

        } else if (!xml_strcmp(name, y_dot1as_ptp_N_rx_pdelay_resp_follow_up_count)) {
            /* leaf rx-pdelay-resp-follow-up-count (uint32) */

        } else if (!xml_strcmp(name, y_dot1as_ptp_N_rx_announce_count)) {
            /* leaf rx-announce-count (uint32) */

        } else if (!xml_strcmp(name, y_dot1as_ptp_N_tx_sync_count)) {
            /* leaf tx-sync-count (uint32) */

        } else if (!xml_strcmp(name, y_dot1as_ptp_N_tx_follow_up_count)) {
            /* leaf tx-follow-up-count (uint32) */

        } else if (!xml_strcmp(name, y_dot1as_ptp_N_tx_pdelay_req_count)) {
            /* leaf tx-pdelay-req-count (uint32) */

        } else if (!xml_strcmp(name, y_dot1as_ptp_N_tx_pdelay_resp_count)) {
            /* leaf tx-pdelay-resp-count (uint32) */

        } else if (!xml_strcmp(name, y_dot1as_ptp_N_tx_pdelay_resp_follow_up_count)) {
            /* leaf tx-pdelay-resp-follow-up-count (uint32) */

        } else if (!xml_strcmp(name, y_dot1as_ptp_N_tx_announce_count)) {
            /* leaf tx-announce-count (uint32) */

        }
    }

    return res;

} /* u_dot1as_ptp_port_statistics_ds_get */



/**
 * @brief Phase 1: Initialize the ieee802-dot1as-ptp server instrumentation library.
 *
 * Called by server when module is loaded.
 *
 * @param modname requested module name to load
 * @param revision requested revision date of the module to load.
 * This may be NULL if the module has no revision statements.
 * @return return status. An error will cause the module load to fail.
 */
status_t u_ieee802_dot1as_ptp_init (
    const xmlChar *modname,
    const xmlChar *revision)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter u_ieee802_dot1as_ptp_init");
    }

    ncx_module_t *ieee802_dot1as_ptp_mod = NULL;

    ieee802_dot1as_ptp_mod = ncx_find_module(modname, revision);
    if (ieee802_dot1as_ptp_mod == NULL) {
        return ERR_NCX_OPERATION_FAILED;
    }

    /* put your module initialization code here */

    return res;

} /* u_ieee802_dot1as_ptp_init */


/**
 * @brief Phase 2: Initialize the ieee802-dot1as-ptp server instrumentation library.
 *
 * SIL init phase 2: non-config data structures.
 * Called after running config is loaded.
 *
 * @return return status. An error will cause the
 * server initialization to fail.
 */
status_t u_ieee802_dot1as_ptp_init2 (void)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter u_ieee802_dot1as_ptp_init2");
    }


    /* put your init2 code here */

    return res;

} /* u_ieee802_dot1as_ptp_init2 */


/**
 * @brief Cleanup the ieee802-dot1as-ptp server instrumentation library.
 *
 * Called by server when module is unloaded.
 *
 */
void u_ieee802_dot1as_ptp_cleanup (void)
{

    if (LOGDEBUG) {
        log_debug("\nEnter u_ieee802_dot1as_ptp_cleanup");
    }


    /* put your cleanup code here */

} /* u_ieee802_dot1as_ptp_cleanup */


 /** @} */

/* END SIL-SA u_ieee802-dot1as-ptp.c */
