/*
 * Copyright (c) 2023 Texas Instruments Incorporated
 * Copyright (c) 2023 Excelfore Corporation (https://excelfore.com)
 *
 * All rights reserved not granted herein.
 * Limited License.
 *
 * Texas Instruments Incorporated grants a world-wide, royalty-free,
 * non-exclusive license under copyrights and patents it now or hereafter
 * owns or controls to make, have made, use, import, offer to sell and sell ("Utilize")
 * this software subject to the terms herein. With respect to the foregoing patent
 * license, such license is granted solely to the extent that any such patent is necessary
 * to Utilize the software alone. The patent license shall not apply to any combinations which
 * include this software, other than combinations with devices manufactured by or for TI ("TI Devices").
 * No hardware patent is licensed hereunder.
 *
 * Redistributions must preserve existing copyright notices and reproduce this license (including the
 * above copyright notice and the disclaimer and (if applicable) source code license limitations below)
 * in the documentation and/or other materials provided with the distribution
 *
 * Redistribution and use in binary form, without modification, are permitted provided that the following
 * conditions are met:
 *
 * * No reverse engineering, decompilation, or disassembly of this software is permitted with respect to any
 * software provided in binary form.
 * * any redistribution and use are licensed by TI for use only with TI Devices.
 * * Nothing shall obligate TI to provide you with source code for the software licensed and provided to you in object code.
 *
 * If software source code is provided to you, modification and redistribution of the source code are permitted
 * provided that the following conditions are met:
 *
 * * any redistribution and use of the source code, including any resulting derivative works, are licensed by
 * TI for use only with TI Devices.
 * * any redistribution and use of any object code compiled from the source code and any resulting derivative
 * works, are licensed by TI for use only with TI Devices.
 *
 * Neither the name of Texas Instruments Incorporated nor the names of its suppliers may be used to endorse or
 * promote products derived from this software without specific prior written permission.
 *
 * DISCLAIMER.
 *
 * THIS SOFTWARE IS PROVIDED BY TI AND TI"S LICENSORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL TI AND TI"S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
*/

/*
 * Copyright (c) 2008 - 2012, Andy Bierman, All Rights Reserved.
 * Copyright (c) 2012 - 2022, YumaWorks, Inc., All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */

/**
 * @file y_ieee802-dot1as-ptp.c
 * @brief YumaPro SIL-SA module for module ieee802-dot1as-ptp
 *

*** Generated by yangdump-sdk 21.10-12

<pre>

    YumaPro SIL-SA module
    bundle x4ucsilsa
    module ieee802-dot1as-ptp
    revision 2022-12-14
    prefix dot1as-ptp
    namespace urn:ieee:std:802.1AS:yang:ieee802-dot1as-ptp
    organization IEEE 802.1 Working Group
    Created: 2023-03-29T06:45:58Z

Online Developer Manual:
https://www.yumaworks.com/pub/21.10/dev/yumapro-dev-manual.html

    CLI parameters:
        defnames true
        deviation excelfore-interfaces
        deviation excelfore-gptp
        format yc
        indent 4
        module ietf-interfaces
        module ieee802-dot1q-bridge
        module ieee802-dot1q-tsn-config-uni
        module excelfore-interfaces
        module ieee1588-ptp
        module ieee802-dot1as-ptp
        module excelfore-gptp
        sil-bundle x4ucsilsa
        sil-edit2
        sil-get2
        sil-include tsn_uniconf/yangs/yang_db_access.h
        sil-include tsn_uniconf/yangs/yang_modules.h
        sil-sa
        unified true

  Short Name Mappings
    allowed_faults = /ptp/instances/instance/ports/port/port-ds/allowed-faults
    allowed_faults_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/allowed-faults
    allowed_lost_responses = /ptp/instances/instance/ports/port/port-ds/allowed-lost-responses
    allowed_lost_responses_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/allowed-lost-responses
    announce_receipt_timeout_count = /ptp/instances/instance/ports/port/port-statistics-ds/announce-receipt-timeout-count
    as_capable = /ptp/instances/instance/ports/port/port-ds/as-capable
    as_capable_across_domains = /ptp/common-services/cmlds/ports/port/link-port-ds/as-capable-across-domains
    asymmetry_measurement_mode_ds = /ptp/instances/instance/ports/port/asymmetry-measurement-mode-ds
    asymmetry_measurement_mode_ds_1 = /ptp/common-services/cmlds/ports/port/asymmetry-measurement-mode-ds
    cmlds_link_port_enabled = /ptp/common-services/cmlds/ports/port/link-port-ds/cmlds-link-port-enabled
    cumulative_rate_ratio = /ptp/instances/instance/parent-ds/cumulative-rate-ratio
    current_compute_mean_link_delay = /ptp/instances/instance/ports/port/port-ds/current-compute-mean-link-delay
    current_compute_mean_link_delay_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/current-compute-mean-link-delay
    current_compute_rate_ratio = /ptp/instances/instance/ports/port/port-ds/current-compute-rate-ratio
    current_compute_rate_ratio_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/current-compute-rate-ratio
    current_log_announce_interval = /ptp/instances/instance/ports/port/port-ds/current-log-announce-interval
    current_log_gptp_cap_interval = /ptp/instances/instance/ports/port/port-ds/current-log-gptp-cap-interval
    current_log_pdelay_req_interval = /ptp/instances/instance/ports/port/port-ds/current-log-pdelay-req-interval
    current_log_pdelay_req_interval_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/current-log-pdelay-req-interval
    current_log_sync_interval = /ptp/instances/instance/ports/port/port-ds/current-log-sync-interval
    current_one_step_tx_oper = /ptp/instances/instance/ports/port/port-ds/current-one-step-tx-oper
    current_utc_offset = /ptp/instances/instance/default-ds/current-utc-offset
    current_utc_offset_valid = /ptp/instances/instance/default-ds/current-utc-offset-valid
    enabled = /ptp/instances/instance/ports/port/asymmetry-measurement-mode-ds/enabled
    enabled_1 = /ptp/common-services/cmlds/ports/port/asymmetry-measurement-mode-ds/enabled
    frequency_traceable = /ptp/instances/instance/default-ds/frequency-traceable
    gm_capable = /ptp/instances/instance/default-ds/gm-capable
    gm_change_count = /ptp/instances/instance/current-ds/gm-change-count
    gm_timebase_indicator = /ptp/instances/instance/current-ds/gm-timebase-indicator
    gptp_cap_receipt_timeout = /ptp/instances/instance/ports/port/port-ds/gptp-cap-receipt-timeout
    initial_compute_mean_link_delay = /ptp/instances/instance/ports/port/port-ds/initial-compute-mean-link-delay
    initial_compute_mean_link_delay_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/initial-compute-mean-link-delay
    initial_compute_rate_ratio = /ptp/instances/instance/ports/port/port-ds/initial-compute-rate-ratio
    initial_compute_rate_ratio_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/initial-compute-rate-ratio
    initial_log_announce_interval = /ptp/instances/instance/ports/port/port-ds/initial-log-announce-interval
    initial_log_gptp_cap_interval = /ptp/instances/instance/ports/port/port-ds/initial-log-gptp-cap-interval
    initial_log_pdelay_req_interval = /ptp/instances/instance/ports/port/port-ds/initial-log-pdelay-req-interval
    initial_log_pdelay_req_interval_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/initial-log-pdelay-req-interval
    initial_log_sync_interval = /ptp/instances/instance/ports/port/port-ds/initial-log-sync-interval
    initial_one_step_tx_oper = /ptp/instances/instance/ports/port/port-ds/initial-one-step-tx-oper
    is_measuring_delay = /ptp/instances/instance/ports/port/port-ds/is-measuring-delay
    is_measuring_delay_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/is-measuring-delay
    last_gm_freq_change = /ptp/instances/instance/current-ds/last-gm-freq-change
    last_gm_phase_change = /ptp/instances/instance/current-ds/last-gm-phase-change
    leap59 = /ptp/instances/instance/default-ds/leap59
    leap61 = /ptp/instances/instance/default-ds/leap61
    mean_link_delay_thresh = /ptp/instances/instance/ports/port/port-ds/mean-link-delay-thresh
    mean_link_delay_thresh_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/mean-link-delay-thresh
    mgt_compute_mean_link_delay = /ptp/instances/instance/ports/port/port-ds/mgt-compute-mean-link-delay
    mgt_compute_mean_link_delay_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/mgt-compute-mean-link-delay
    mgt_compute_rate_ratio = /ptp/instances/instance/ports/port/port-ds/mgt-compute-rate-ratio
    mgt_compute_rate_ratio_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/mgt-compute-rate-ratio
    mgt_log_gptp_cap_interval = /ptp/instances/instance/ports/port/port-ds/mgt-log-gptp-cap-interval
    mgt_log_pdelay_req_interval = /ptp/instances/instance/ports/port/port-ds/mgt-log-pdelay-req-interval
    mgt_log_pdelay_req_interval_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/mgt-log-pdelay-req-interval
    mgt_one_step_tx_oper = /ptp/instances/instance/ports/port/port-ds/mgt-one-step-tx-oper
    ndown = /ptp/instances/instance/ports/port/port-ds/ndown
    neighbor_rate_ratio = /ptp/instances/instance/ports/port/port-ds/neighbor-rate-ratio
    nup = /ptp/instances/instance/ports/port/port-ds/nup
    one_step_receive = /ptp/instances/instance/ports/port/port-ds/one-step-receive
    one_step_transmit = /ptp/instances/instance/ports/port/port-ds/one-step-transmit
    one_step_tx_oper = /ptp/instances/instance/ports/port/port-ds/one-step-tx-oper
    pdelay_allowed_lost_exceeded_count = /ptp/instances/instance/ports/port/port-statistics-ds/pdelay-allowed-lost-exceeded-count
    pdelay_allowed_lost_exceeded_count_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds/pdelay-allowed-lost-exceeded-count
    pdelay_truncated_timestamps = /ptp/instances/instance/ports/port/port-ds/pdelay-truncated-timestamps
    pdelay_truncated_timestamps_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/pdelay-truncated-timestamps
    port_statistics_ds = /ptp/instances/instance/ports/port/port-statistics-ds
    port_statistics_ds_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds
    ptp_timescale = /ptp/instances/instance/default-ds/ptp-timescale
    rx_announce_count = /ptp/instances/instance/ports/port/port-statistics-ds/rx-announce-count
    rx_follow_up_count = /ptp/instances/instance/ports/port/port-statistics-ds/rx-follow-up-count
    rx_one_step_sync_count = /ptp/instances/instance/ports/port/port-statistics-ds/rx-one-step-sync-count
    rx_packet_discard_count = /ptp/instances/instance/ports/port/port-statistics-ds/rx-packet-discard-count
    rx_packet_discard_count_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds/rx-packet-discard-count
    rx_pdelay_req_count = /ptp/instances/instance/ports/port/port-statistics-ds/rx-pdelay-req-count
    rx_pdelay_req_count_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds/rx-pdelay-req-count
    rx_pdelay_resp_count = /ptp/instances/instance/ports/port/port-statistics-ds/rx-pdelay-resp-count
    rx_pdelay_resp_count_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds/rx-pdelay-resp-count
    rx_pdelay_resp_follow_up_count = /ptp/instances/instance/ports/port/port-statistics-ds/rx-pdelay-resp-follow-up-count
    rx_pdelay_resp_follow_up_count_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds/rx-pdelay-resp-follow-up-count
    rx_sync_count = /ptp/instances/instance/ports/port/port-statistics-ds/rx-sync-count
    sync_locked = /ptp/instances/instance/ports/port/port-ds/sync-locked
    sync_receipt_timeout = /ptp/instances/instance/ports/port/port-ds/sync-receipt-timeout
    sync_receipt_timeout_count = /ptp/instances/instance/ports/port/port-statistics-ds/sync-receipt-timeout-count
    sync_receipt_timeout_interval = /ptp/instances/instance/ports/port/port-ds/sync-receipt-timeout-interval
    time_of_last_freq_change = /ptp/instances/instance/current-ds/time-of-last-freq-change
    time_of_last_gm_change = /ptp/instances/instance/current-ds/time-of-last-gm-change
    time_of_last_phase_change = /ptp/instances/instance/current-ds/time-of-last-phase-change
    time_source = /ptp/instances/instance/default-ds/time-source
    time_traceable = /ptp/instances/instance/default-ds/time-traceable
    tx_announce_count = /ptp/instances/instance/ports/port/port-statistics-ds/tx-announce-count
    tx_follow_up_count = /ptp/instances/instance/ports/port/port-statistics-ds/tx-follow-up-count
    tx_one_step_sync_count = /ptp/instances/instance/ports/port/port-statistics-ds/tx-one-step-sync-count
    tx_pdelay_req_count = /ptp/instances/instance/ports/port/port-statistics-ds/tx-pdelay-req-count
    tx_pdelay_req_count_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds/tx-pdelay-req-count
    tx_pdelay_resp_count = /ptp/instances/instance/ports/port/port-statistics-ds/tx-pdelay-resp-count
    tx_pdelay_resp_count_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds/tx-pdelay-resp-count
    tx_pdelay_resp_follow_up_count = /ptp/instances/instance/ports/port/port-statistics-ds/tx-pdelay-resp-follow-up-count
    tx_pdelay_resp_follow_up_count_1 = /ptp/common-services/cmlds/ports/port/port-statistics-ds/tx-pdelay-resp-follow-up-count
    tx_sync_count = /ptp/instances/instance/ports/port/port-statistics-ds/tx-sync-count
    use_mgt_compute_mean_link_delay = /ptp/instances/instance/ports/port/port-ds/use-mgt-compute-mean-link-delay
    use_mgt_compute_mean_link_delay_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/use-mgt-compute-mean-link-delay
    use_mgt_compute_rate_ratio = /ptp/instances/instance/ports/port/port-ds/use-mgt-compute-rate-ratio
    use_mgt_compute_rate_ratio_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/use-mgt-compute-rate-ratio
    use_mgt_log_announce_interval = /ptp/instances/instance/ports/port/port-ds/use-mgt-log-announce-interval
    use_mgt_log_gptp_cap_interval = /ptp/instances/instance/ports/port/port-ds/use-mgt-log-gptp-cap-interval
    use_mgt_log_pdelay_req_interval = /ptp/instances/instance/ports/port/port-ds/use-mgt-log-pdelay-req-interval
    use_mgt_log_pdelay_req_interval_1 = /ptp/common-services/cmlds/ports/port/link-port-ds/use-mgt-log-pdelay-req-interval
    use_mgt_log_sync_interval = /ptp/instances/instance/ports/port/port-ds/use-mgt-log-sync-interval
    use_mgt_one_step_tx_oper = /ptp/instances/instance/ports/port/port-ds/use-mgt-one-step-tx-oper
</pre>

 */

#include <xmlstring.h>

#include "procdefs.h"
#include "agt.h"
#include "agt_action.h"
#include "agt_cb.h"
#include "agt_cfg.h"
#include "agt_rpc.h"
#include "agt_sil_lib.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "agt_val.h"
#include "cfg.h"
#include "dlq.h"
#include "getcb.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "obj.h"
#include "rpc.h"
#include "sil_sa.h"
#include "status.h"
#include "val.h"
#include "val_child.h"
#include "val_util.h"
#include "xml_val.h"

#include "tsn_uniconf/yangs/yang_db_access.h"
#include "tsn_uniconf/yangs/yang_modules.h"


/* SIL bundle: x4ucsilsa */
#include "y_ietf-interfaces.h"
#include "u_ietf-interfaces.h"
#include "y_ieee802-dot1q-bridge.h"
#include "u_ieee802-dot1q-bridge.h"
#include "y_ieee802-dot1q-tsn-config-uni.h"
#include "u_ieee802-dot1q-tsn-config-uni.h"
#include "y_excelfore-interfaces.h"
#include "u_excelfore-interfaces.h"
#include "y_ieee1588-ptp.h"
#include "u_ieee1588-ptp.h"
#include "y_ieee802-dot1as-ptp.h"
#include "u_ieee802-dot1as-ptp.h"
#include "y_excelfore-gptp.h"
#include "u_excelfore-gptp.h"


/**
 * @addtogroup yang-library YANG Library
 *
 * Collection of modules supported by the server.
 * Generated by yangdump-sdk.
 */



/**
 * @addtogroup silsa-x4ucsilsa-ieee802-dot1as-ptp Module ieee802-dot1as-ptp in Bundle x4ucsilsa
 * @ingroup silsa-x4ucsilsa
 *
 * @{
 *
 * YANG instrumentation library.
 * Generated by yangdump-sdk.
 */


/* module static variables */
static ncx_module_t *ieee802_dot1as_ptp_mod;

/**
 * @brief Initialize module static variables
 *
 * Called by server when module is loaded.
 */
static void y_dot1as_ptp_init_static_vars (void)
{
    ieee802_dot1as_ptp_mod = NULL;

} /* y_dot1as_ptp_init_static_vars */


/**
 * @brief Get database object callback for leaf gm-capable (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/gm-capable\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t gm_capable_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter gm_capable_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    return u_dot1as_ptp_gm_capable_get(
        get2cb,
        k_ptp_instance_index);

} /* gm_capable_get */


/**
 * @brief Get database object callback for leaf current-utc-offset (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/current-utc-offset\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t current_utc_offset_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter current_utc_offset_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    return u_dot1as_ptp_current_utc_offset_get(
        get2cb,
        k_ptp_instance_index);

} /* current_utc_offset_get */


/**
 * @brief Get database object callback for leaf current-utc-offset-valid (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/current-utc-offset-valid\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t current_utc_offset_valid_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter current_utc_offset_valid_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    return u_dot1as_ptp_current_utc_offset_valid_get(
        get2cb,
        k_ptp_instance_index);

} /* current_utc_offset_valid_get */


/**
 * @brief Get database object callback for leaf leap59 (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/leap59\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t leap59_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter leap59_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    return u_dot1as_ptp_leap59_get(
        get2cb,
        k_ptp_instance_index);

} /* leap59_get */


/**
 * @brief Get database object callback for leaf leap61 (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/leap61\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t leap61_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter leap61_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    return u_dot1as_ptp_leap61_get(
        get2cb,
        k_ptp_instance_index);

} /* leap61_get */


/**
 * @brief Get database object callback for leaf time-traceable (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/time-traceable\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t time_traceable_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter time_traceable_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    return u_dot1as_ptp_time_traceable_get(
        get2cb,
        k_ptp_instance_index);

} /* time_traceable_get */


/**
 * @brief Get database object callback for leaf frequency-traceable (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/frequency-traceable\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t frequency_traceable_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter frequency_traceable_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    return u_dot1as_ptp_frequency_traceable_get(
        get2cb,
        k_ptp_instance_index);

} /* frequency_traceable_get */


/**
 * @brief Get database object callback for leaf ptp-timescale (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/ptp-timescale\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t ptp_timescale_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter ptp_timescale_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    return u_dot1as_ptp_ptp_timescale_get(
        get2cb,
        k_ptp_instance_index);

} /* ptp_timescale_get */


/**
 * @brief Get database object callback for leaf time-source (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/default-ds/time-source\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t time_source_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter time_source_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    return u_dot1as_ptp_time_source_get(
        get2cb,
        k_ptp_instance_index);

} /* time_source_get */


/**
 * @brief Get database object callback for leaf is-measuring-delay (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/is-measuring-delay\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t is_measuring_delay_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter is_measuring_delay_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_is_measuring_delay_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* is_measuring_delay_get */


/**
 * @brief Get database object callback for leaf as-capable (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/as-capable\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t as_capable_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter as_capable_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_as_capable_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* as_capable_get */


/**
 * @brief Get database object callback for leaf neighbor-rate-ratio (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/neighbor-rate-ratio\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t neighbor_rate_ratio_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter neighbor_rate_ratio_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_neighbor_rate_ratio_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* neighbor_rate_ratio_get */


/**
 * @brief Get database object callback for leaf current-log-announce-interval (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/current-log-announce-interval\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t current_log_announce_interval_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter current_log_announce_interval_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_current_log_announce_interval_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* current_log_announce_interval_get */


/**
 * @brief Get database object callback for leaf use-mgt-log-announce-interval (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/use-mgt-log-announce-interval\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t use_mgt_log_announce_interval_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter use_mgt_log_announce_interval_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_use_mgt_log_announce_interval_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* use_mgt_log_announce_interval_get */


/**
 * @brief Get database object callback for leaf current-log-sync-interval (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/current-log-sync-interval\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t current_log_sync_interval_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter current_log_sync_interval_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_current_log_sync_interval_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* current_log_sync_interval_get */


/**
 * @brief Get database object callback for leaf use-mgt-log-sync-interval (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/use-mgt-log-sync-interval\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t use_mgt_log_sync_interval_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter use_mgt_log_sync_interval_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_use_mgt_log_sync_interval_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* use_mgt_log_sync_interval_get */


/**
 * @brief Get database object callback for leaf sync-receipt-timeout-interval (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/sync-receipt-timeout-interval\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t sync_receipt_timeout_interval_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter sync_receipt_timeout_interval_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_sync_receipt_timeout_interval_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* sync_receipt_timeout_interval_get */


/**
 * @brief Get database object callback for leaf current-log-pdelay-req-interval (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/current-log-pdelay-req-interval\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t current_log_pdelay_req_interval_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter current_log_pdelay_req_interval_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_current_log_pdelay_req_interval_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* current_log_pdelay_req_interval_get */


/**
 * @brief Get database object callback for leaf use-mgt-log-pdelay-req-interval (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/use-mgt-log-pdelay-req-interval\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t use_mgt_log_pdelay_req_interval_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter use_mgt_log_pdelay_req_interval_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_use_mgt_log_pdelay_req_interval_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* use_mgt_log_pdelay_req_interval_get */


/**
 * @brief Get database object callback for leaf current-log-gptp-cap-interval (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/current-log-gptp-cap-interval\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t current_log_gptp_cap_interval_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter current_log_gptp_cap_interval_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_current_log_gptp_cap_interval_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* current_log_gptp_cap_interval_get */


/**
 * @brief Get database object callback for leaf use-mgt-compute-rate-ratio (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/use-mgt-compute-rate-ratio\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t use_mgt_compute_rate_ratio_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter use_mgt_compute_rate_ratio_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_use_mgt_compute_rate_ratio_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* use_mgt_compute_rate_ratio_get */


/**
 * @brief Get database object callback for leaf use-mgt-compute-mean-link-delay (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/use-mgt-compute-mean-link-delay\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t use_mgt_compute_mean_link_delay_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter use_mgt_compute_mean_link_delay_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_use_mgt_compute_mean_link_delay_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* use_mgt_compute_mean_link_delay_get */


/**
 * @brief Get database object callback for leaf one-step-tx-oper (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/one-step-tx-oper\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t one_step_tx_oper_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter one_step_tx_oper_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_one_step_tx_oper_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* one_step_tx_oper_get */


/**
 * @brief Get database object callback for leaf one-step-receive (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/one-step-receive\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t one_step_receive_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter one_step_receive_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_one_step_receive_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* one_step_receive_get */


/**
 * @brief Get database object callback for leaf one-step-transmit (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/one-step-transmit\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t one_step_transmit_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter one_step_transmit_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_one_step_transmit_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* one_step_transmit_get */


/**
 * @brief Get database object callback for leaf initial-one-step-tx-oper (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/initial-one-step-tx-oper\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t initial_one_step_tx_oper_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter initial_one_step_tx_oper_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_initial_one_step_tx_oper_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* initial_one_step_tx_oper_get */


/**
 * @brief Get database object callback for leaf current-one-step-tx-oper (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/current-one-step-tx-oper\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t current_one_step_tx_oper_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter current_one_step_tx_oper_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_current_one_step_tx_oper_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* current_one_step_tx_oper_get */


/**
 * @brief Get database object callback for leaf use-mgt-one-step-tx-oper (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/use-mgt-one-step-tx-oper\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t use_mgt_one_step_tx_oper_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter use_mgt_one_step_tx_oper_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_use_mgt_one_step_tx_oper_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* use_mgt_one_step_tx_oper_get */


/**
 * @brief Get database object callback for leaf mgt-one-step-tx-oper (getcb_fn2_t)\n
 * Path: leaf /ptp/instances/instance/ports/port/port-ds/mgt-one-step-tx-oper\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t mgt_one_step_tx_oper_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter mgt_one_step_tx_oper_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_mgt_one_step_tx_oper_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* mgt_one_step_tx_oper_get */


/**
 * @brief Get database object callback for leaf-list pdelay-truncated-timestamps (getcb_fn2_t)\n
 * Path: leaf-list /ptp/instances/instance/ports/port/port-ds/pdelay-truncated-timestamps\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t pdelay_truncated_timestamps_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter pdelay_truncated_timestamps_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_pdelay_truncated_timestamps_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* pdelay_truncated_timestamps_get */


/**
 * @brief Get database object callback for container port-statistics-ds (getcb_fn2_t)\n
 * Path: container /ptp/instances/instance/ports/port/port-statistics-ds\n
 *
 * Fill in 'get2cb' response fields.
 *
 * @param scb session control block making the request.
 * @param msg message in progress for this retrieval request.
 * @param get2cb GET2 control block for the callback.
 * @return return status of the callback.
 */
static status_t port_statistics_ds_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    if (LOGDEBUG) {
        log_debug("\nEnter port_statistics_ds_get");
    }

    (void)scb;
    (void)msg;

    val_value_t *keyval = NULL;

    /* ancestor key ieee1588-ptp:instance-index */
    uint32 k_ptp_instance_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_instance_index,
        (uint32)4);
    if (keyval) {
        k_ptp_instance_index = VAL_UINT(keyval);
    }

    /* ancestor key ieee1588-ptp:port-index */
    uint16 k_ptp_port_index = 0;
    keyval = getcb_find_key_lvl(get2cb,
        y_ptp_M_ptp,
        y_ptp_N_port_index,
        (uint32)6);
    if (keyval) {
        k_ptp_port_index = VAL_UINT16(keyval);
    }

    return u_dot1as_ptp_port_statistics_ds_get(
        get2cb,
        k_ptp_instance_index,
        k_ptp_port_index);

} /* port_statistics_ds_get */


/**
 * @brief Phase 1: Initialize the ieee802-dot1as-ptp server instrumentation library.
 *
 * Called by server when module is loaded.
 *
 * @param modname requested module name to load
 * @param revision requested revision date of the module to load.
 * This may be NULL if the module has no revision statements.
 * @return return status. An error will cause the module load to fail.
 */
status_t y_ieee802_dot1as_ptp_init (
    const xmlChar *modname,
    const xmlChar *revision)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter y_ieee802_dot1as_ptp_init");
    }


    y_dot1as_ptp_init_static_vars();

    /* change if custom handling done */
    if (xml_strcmp(modname, y_dot1as_ptp_M_dot1as_ptp)) {
        return ERR_NCX_UNKNOWN_MODULE;
    }

    if (revision && xml_strcmp(revision, y_dot1as_ptp_R_dot1as_ptp)) {
        return ERR_NCX_WRONG_VERSION;
    }

    res = ncxmod_load_module(
        y_dot1as_ptp_M_dot1as_ptp,
        y_dot1as_ptp_R_dot1as_ptp,
        agt_get_savedevQ(),
        &ieee802_dot1as_ptp_mod);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:default-ds/dot1as-ptp:gm-capable",
        y_dot1as_ptp_R_dot1as_ptp,
        gm_capable_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:default-ds/dot1as-ptp:current-utc-offset",
        y_dot1as_ptp_R_dot1as_ptp,
        current_utc_offset_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:default-ds/dot1as-ptp:current-utc-offset-valid",
        y_dot1as_ptp_R_dot1as_ptp,
        current_utc_offset_valid_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:default-ds/dot1as-ptp:leap59",
        y_dot1as_ptp_R_dot1as_ptp,
        leap59_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:default-ds/dot1as-ptp:leap61",
        y_dot1as_ptp_R_dot1as_ptp,
        leap61_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:default-ds/dot1as-ptp:time-traceable",
        y_dot1as_ptp_R_dot1as_ptp,
        time_traceable_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:default-ds/dot1as-ptp:frequency-traceable",
        y_dot1as_ptp_R_dot1as_ptp,
        frequency_traceable_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:default-ds/dot1as-ptp:ptp-timescale",
        y_dot1as_ptp_R_dot1as_ptp,
        ptp_timescale_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:default-ds/dot1as-ptp:time-source",
        y_dot1as_ptp_R_dot1as_ptp,
        time_source_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:is-measuring-delay",
        y_dot1as_ptp_R_dot1as_ptp,
        is_measuring_delay_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:as-capable",
        y_dot1as_ptp_R_dot1as_ptp,
        as_capable_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:neighbor-rate-ratio",
        y_dot1as_ptp_R_dot1as_ptp,
        neighbor_rate_ratio_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:current-log-announce-interval",
        y_dot1as_ptp_R_dot1as_ptp,
        current_log_announce_interval_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:use-mgt-log-announce-interval",
        y_dot1as_ptp_R_dot1as_ptp,
        use_mgt_log_announce_interval_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:current-log-sync-interval",
        y_dot1as_ptp_R_dot1as_ptp,
        current_log_sync_interval_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:use-mgt-log-sync-interval",
        y_dot1as_ptp_R_dot1as_ptp,
        use_mgt_log_sync_interval_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:sync-receipt-timeout-interval",
        y_dot1as_ptp_R_dot1as_ptp,
        sync_receipt_timeout_interval_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:current-log-pdelay-req-interval",
        y_dot1as_ptp_R_dot1as_ptp,
        current_log_pdelay_req_interval_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:use-mgt-log-pdelay-req-interval",
        y_dot1as_ptp_R_dot1as_ptp,
        use_mgt_log_pdelay_req_interval_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:current-log-gptp-cap-interval",
        y_dot1as_ptp_R_dot1as_ptp,
        current_log_gptp_cap_interval_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:use-mgt-compute-rate-ratio",
        y_dot1as_ptp_R_dot1as_ptp,
        use_mgt_compute_rate_ratio_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:use-mgt-compute-mean-link-delay",
        y_dot1as_ptp_R_dot1as_ptp,
        use_mgt_compute_mean_link_delay_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:one-step-tx-oper",
        y_dot1as_ptp_R_dot1as_ptp,
        one_step_tx_oper_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:one-step-receive",
        y_dot1as_ptp_R_dot1as_ptp,
        one_step_receive_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:one-step-transmit",
        y_dot1as_ptp_R_dot1as_ptp,
        one_step_transmit_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:initial-one-step-tx-oper",
        y_dot1as_ptp_R_dot1as_ptp,
        initial_one_step_tx_oper_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:current-one-step-tx-oper",
        y_dot1as_ptp_R_dot1as_ptp,
        current_one_step_tx_oper_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:use-mgt-one-step-tx-oper",
        y_dot1as_ptp_R_dot1as_ptp,
        use_mgt_one_step_tx_oper_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:mgt-one-step-tx-oper",
        y_dot1as_ptp_R_dot1as_ptp,
        mgt_one_step_tx_oper_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/ptp:port-ds/dot1as-ptp:pdelay-truncated-timestamps",
        y_dot1as_ptp_R_dot1as_ptp,
        pdelay_truncated_timestamps_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/dot1as-ptp:port-statistics-ds",
        y_dot1as_ptp_R_dot1as_ptp,
        port_statistics_ds_get);
    if (res != NO_ERR) {
        return res;
    }

    res = u_ieee802_dot1as_ptp_init(modname, revision);
    return res;

} /* y_ieee802_dot1as_ptp_init */


/**
 * @brief Phase 2: Initialize the ieee802-dot1as-ptp server instrumentation library.
 *
 * SIL init phase 2: non-config data structures.
 * Called after running config is loaded.
 *
 * @return return status. An error will cause the
 * server initialization to fail.
 */
status_t y_ieee802_dot1as_ptp_init2 (void)
{
    status_t res = NO_ERR;

    if (LOGDEBUG) {
        log_debug("\nEnter y_ieee802_dot1as_ptp_init2");
    }


    res = u_ieee802_dot1as_ptp_init2();

    return res;

} /* y_ieee802_dot1as_ptp_init2 */


/**
 * @brief Cleanup the ieee802-dot1as-ptp server instrumentation library.
 *
 * Called by server when module is unloaded.
 *
 */
void y_ieee802_dot1as_ptp_cleanup (void)
{

    if (LOGDEBUG) {
        log_debug("\nEnter y_ieee802_dot1as_ptp_cleanup");
    }


    agt_cb_unregister_callbacks(
        y_dot1as_ptp_M_dot1as_ptp,
        (const xmlChar *)"/ptp:ptp/ptp:instances/ptp:instance/ptp:ports/ptp:port/dot1as-ptp:port-statistics-ds");

    u_ieee802_dot1as_ptp_cleanup();

} /* y_ieee802_dot1as_ptp_cleanup */


 /** @} */

/* END SIL-SA y_ieee802-dot1as-ptp.c */
